### ISSUE TITLE
Encoding Error

### ISSUE THREAD

**Issue by qhnprof** [lorenzodifuccia/safaribooks#1]
Unhandled Exception: 'charmap' codec can't encode character '\u03c0' 
 Unhandled Exception: 'charmap' codec can't encode character '\u2192' 

Book ID : 0596101538

**Comment by lorenzodifuccia** [comment]
Thanks for the issue, now is fixed.
Pull the program and try to download the book again.
:+1:

**Comment by qhnprof** [comment]
Great, Thank you.
