### ISSUE TITLE
How about using book name instead of id?

### ISSUE THREAD

**Issue by 9bow** [lorenzodifuccia/safaribooks#100]
(As the title I wrote above) how about using book name as for epub file's?

I think the book id is good for machine, not for human.

If you think so, I'll modify the last line of `create_epub()` to use `clean_book_title` (and PR).

Thank you.

**Comment by lorenzodifuccia** [comment]
There ware so many issues about epub file name so I decided to use the ID. I'll leave the PR for others, but I'm closing this issue. Thank you!

**Comment by lorenzodifuccia** [comment]
There ware so many issues about epub file name so I decided to use the ID. I'll leave the PR for others, but I'm closing this issue. Thank you!
