### ISSUE TITLE
Page contents truncated.

### ISSUE THREAD

**Issue by senthilsivanath** [lorenzodifuccia/safaribooks#103]
Used this tool convert pattern recognition book into epub format.  
https://learning.oreilly.com/library/view/pattern-recognition-4th/9781597492720/kindle_split_008.html

Contents at the end of the chapter are truncated. For. e.g 
https://learning.oreilly.com/library/view/pattern-recognition-4th/9781597492720/kindle_split_008.html

had last 3 lines missing in epub format

**Comment by m33k** [comment]
@senthilsivanath Very interesting. Could you provide steps to replicate this issue? Also more info about your environment? OS Version, Python/Pip Version, etc.

**Comment by ginkel** [comment]
I have an even stranger problem. For ISBN 9780133390124 there are multiple chapters that only contain a single page and end with an ellipsis (e.g., chapter 2). To reproduce:

1. Download book:

```
$ python3 ./safaribooks.py  9780133390124
```

2. Inspect chapter 2

**Comment by gleocadie** [comment]
@ginkel You can have a look to #129 
I have a fix (not sure about the reason yet)
I tested it on the book you specified to try reproducing, but it worked (full chapter 2, not truncated)
