### ISSUE TITLE
failed to install. Are you able to assist?

### ISSUE THREAD

**Issue by seasaltseasalt** [lorenzodifuccia/safaribooks#105]
I tried to install your tool
error I receive is below.
thankyou

authorMB:safaribooks author$ pip3 install -r requirements.txt
Collecting lxml>=4.1.1 (from -r requirements.txt (line 1))
  Could not find a version that satisfies the requirement lxml>=4.1.1 (from -r requirements.txt (line 1)) (from versions: )
No matching distribution found for lxml>=4.1.1 (from -r requirements.txt (line 1))

**Comment by m33k** [comment]
Hi @seasaltseasalt What OS version are you using?

I was able to install via pip3 on my end. I'm using CentOS 7 

```
[root@sandbox7 safaribooks]# cat /etc/redhat-release
CentOS Linux release 7.3.1611 (Core)

[root@sandbox7 safaribooks]# python3.6 --version
Python 3.6.1
```
```
[root@sandbox7 safaribooks]# pip3 install -r requirements.txt
Collecting lxml>=4.1.1 (from -r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/2d/53/34a9f0c79c548e430148837892b6ae91adee571a0e8b6c17bd7ff9c2d12e/lxml-4.3.4-cp36-cp36m-manylinux1_x86_64.whl (5.7MB)
    100% |████████████████████████████████| 5.7MB 87kB/s
Collecting requests>=2.20.0 (from -r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/51/bd/23c926cd341ea6b7dd0b2a00aba99ae0f828be89d72b2190f27c11d4b7fb/requests-2.22.0-py2.py3-none-any.whl (57kB)
    100% |████████████████████████████████| 61kB 2.3MB/s
Collecting certifi>=2017.4.17 (from requests>=2.20.0->-r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/69/1b/b853c7a9d4f6a6d00749e94eb6f3a041e342a885b87340b79c1ef73e3a78/certifi-2019.6.16-py2.py3-none-any.whl (157kB)
    100% |████████████████████████████████| 163kB 1.6MB/s
Collecting idna<2.9,>=2.5 (from requests>=2.20.0->-r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/14/2c/cd551d81dbe15200be1cf41cd03869a46fe7226e7450af7a6545bfc474c9/idna-2.8-py2.py3-none-any.whl (58kB)
    100% |████████████████████████████████| 61kB 2.7MB/s
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 (from requests>=2.20.0->-r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/e6/60/247f23a7121ae632d62811ba7f273d0e58972d75e58a94d329d51550a47d/urllib3-1.25.3-py2.py3-none-any.whl (150kB)
    100% |████████████████████████████████| 153kB 1.8MB/s
Collecting chardet<3.1.0,>=3.0.2 (from requests>=2.20.0->-r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl (133kB)
    100% |████████████████████████████████| 143kB 1.7MB/s
Installing collected packages: lxml, certifi, idna, urllib3, chardet, requests
Successfully installed certifi-2019.6.16 chardet-3.0.4 idna-2.8 lxml-4.3.4 requests-2.22.0 urllib3-1.25.3

```

**Comment by seasaltseasalt** [comment]
Sierra 10.12

**Comment by m33k** [comment]
I'd recommend using a virtualenv to install the dependencies for safaribooks. This is best so you don't break system Python on your Mac.

See Tutorial: https://hackercodex.com/guide/python-development-environment-on-mac-osx/

Setup a virtualenv via Python3 and then activate it and pip install the requirements.

**Comment by seasaltseasalt** [comment]
I have python 3.6 installed already for something else

**Comment by seasaltseasalt** [comment]
author:safaribooks author$ pip3 -V
pip 7.1.2 from /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages (python 3.5)

**Comment by m33k** [comment]
The python version you listed is 3.5. If you create the venv, you should be able to install any packages from the pypi repo. Which is located here. https://pypi.org/project/lxml/

Again I'd recommend not install anything on system python to avoid messing up the Python version MacOS comes with.

You can also try to install it manually using `pip3 install lxml`

Let us know how that works for you.
