### ISSUE TITLE
Unhandled Exception

### ISSUE THREAD

**Issue by dexter101010** [lorenzodifuccia/safaribooks#11]
[-] Creating EPUB file...
                                                                                                                        [*] Done: bla bla bla).epub

    If you like it, please * this project on GitHub to make it known:
        https://github.com/lorenzodifuccia/safaribooks
    e don't forget to renew your Safari Books Online subscription:
        https://www.safaribooksonline.com/signup/

Unhandled Exception: [WinError 32] The process cannot access the file because it is being used by another process: 'D:\\safaribooks-master\\info_9781587141485.log' (type: PermissionError)
[27/Mar/2018 19:35:43] Last request done:

This message it is received after the book it's done

**Comment by lorenzodifuccia** [comment]
Did you open the log file before the program tried to delete it?

**Comment by dexter101010** [comment]
No, i did not.I am using win10, Python 3.6.4.

Another example here : 
[-] Creating EPUB file...
                                                                                                                        [*] Done: X.epub

    If you like it, please * this project on GitHub to make it known:
        https://github.com/lorenzodifuccia/safaribooks
    e don't forget to renew your Safari Books Online subscription:
        https://www.safaribooksonline.com/signup/

[!] Bye!!
                                                                                                                        [#] Unhandled Exception: [WinError 32] The process cannot access the file because it is being used by another process: 'D:\\safaribooks-master\\info_aaaaaa.log' (type: PermissionError)
                                                                                                                        [+] Please delete all the `<BOOK NAME>/OEBPS/*.xhtml` files and restart the program.
                                                                                                                        [!] Aborting...

**Comment by lorenzodifuccia** [comment]
It's weird...
Does Python have the permission to delete file on that partition?

**Comment by dexter101010** [comment]
I am running the script from a command promt line with Administrator rights, so i guess it does have all the rights.It is not really an issue.The book it's created but in the end it give that error.Thanks for your hard work.I really enjoy this one.Maybe you can do some other scripts for sites like : INE, CBTNuggets, Amazon.For Safari videos i saw that you can use youtube-dl but the problem with that is you cannot choose the quality that you want so in the end you will download the highest quality and then you need to convert it so it does not take so much space on your hdd.

**Comment by gluekeng** [comment]
I found the same error also. I guess it is related to Log Handler which you do not close before removing log files. Then Windows will lock these files and not release when need to remove it.
