### ISSUE TITLE
Project license

### ISSUE THREAD

**Issue by JoaoGFarias** [lorenzodifuccia/safaribooks#112]
For what I could see, the project itself doesn't have any license - so I am not sure what people can do with code itself.

IMO, some good licenses that may fit the intent of the project are [GPL v2](http://oss-watch.ac.uk/resources/gpl), [BSD](https://opensource.org/licenses/BSD-2-Clause), and [WTFPL](http://www.wtfpl.net/)

**Comment by lorenzodifuccia** [comment]
I'll adopt the WTFPL...
Thanks 😆

**Comment by lorenzodifuccia** [comment]
Closed in #950a3c7
