### ISSUE TITLE
TypeError: decoding str is not supported

### ISSUE THREAD

**Issue by lurodri** [lorenzodifuccia/safaribooks#115]
Running it with the following command:

python3 safaribooks.py --cred "lrodrigues@gmail.com:pass" 9781491983638

Gets the following error message:

Error in sys.excepthook:
Traceback (most recent call last):
  File "safaribooks.py", line 104, in unhandled_exception
    self.exit("Unhandled Exception: %s (type: %s)" % (o, o.__class__.__name__))
  File "safaribooks.py", line 90, in exit
    self.error(str(error))
  File "safaribooks.py", line 87, in error
    self.out(output)
  File "safaribooks.py", line 73, in out
    sys.stdout.write("\r" + " " * self.columns + "\r" + str(put, "utf-8", "replace") + "\n")
TypeError: decoding str is not supported

Original exception was:
Traceback (most recent call last):
  File "safaribooks.py", line 1039, in <module>
    SafariBooks(args_parsed)
  File "safaribooks.py", line 281, in __init__
    self.display.intro()
  File "safaribooks.py", line 123, in intro
    self.out(output)
  File "safaribooks.py", line 73, in out
    sys.stdout.write("\r" + " " * self.columns + "\r" + str(put, "utf-8", "replace") + "\n")
TypeError: decoding str is not supported

**Comment by gudata** [comment]
temporary fix change 73 line to:

```
        sys.stdout.write("\r" + put + "\n")
```

**Comment by grexe** [comment]
thanks @gudata , had the same issue and this helped. Could you do a PR and ping the author?

**Comment by varta2014** [comment]
hi how add this please 
temporary fix change 73 line to:

        sys.stdout.write("\r" + put + "\n")

can show me in image please

**Comment by davistran86** [comment]
> hi how add this please
> temporary fix change 73 line to:
> 
> ```
>     sys.stdout.write("\r" + put + "\n")
> ```
> 
> can show me in image please

@varta2014 open file safaribooks.py with some text editor then go to line 73, replace that line with above

**Comment by stblack** [comment]
I used this temporary fix and it worked for me to download a book
