### ISSUE TITLE
Where is Lorenzo?

### ISSUE THREAD

**Issue by m33k** [lorenzodifuccia/safaribooks#121]
@lorenzodifuccia Thanks for this script. I've used it a few times. 
Are you available to merge some pull requests?

The community is trying to help, but were limited. Feel free to give a trusted user direct contributor access if you need help or are too busy for the project.

**Comment by lorenzodifuccia** [comment]
Find me good candidates...

**Comment by kiawin** [comment]
Hi, I would like to assist, if that's ok with you :)

**Comment by TheSnoozer** [comment]
Hi, I would also be happy to help out....

**Comment by hazcod** [comment]
ping @lorenzodifuccia

**Comment by obar1** [comment]
you can always fork and fix and open mr ;) that is the right way 
https://github.com/tpiechaczek/safaribooks
https://github.com/elrob/safaribooks
https://github.com/zqlu/safaribooks

ciao @lorenzodifuccia

**Comment by TheSnoozer** [comment]
For comparison what those repos include:
https://github.com/lorenzodifuccia/safaribooks/compare/master...tpiechaczek:master
https://github.com/lorenzodifuccia/safaribooks/compare/master...elrob:master
https://github.com/lorenzodifuccia/safaribooks/compare/master...zqlu:master


See also https://github.com/TheSnoozer/safaribooks

or https://github.com/lorenzodifuccia/safaribooks/compare/master...TheSnoozer:master

**Comment by diegorodriguezv** [comment]
I can help too!
I think the most difficult problem is not technical but "social". We need to develop a community and a process to take weight off Lorenzo's shoulders. He can be some sort of BDFL, while other people help with fixes and features but specially with communication and coordination.
