### ISSUE TITLE
The site, and all content and other elements available on or through the site, are the property of Safari and/or its content providers, and are protected by the laws of the United States and other countries, including their copyright and trademark laws. Your use of the site does not transfer to you any ownership or other rights in the site or its content. The site may not be copied, reproduced, republished, uploaded, transmitted, modified, indexed, catalogued, mirrored or distributed in any way, in whole or in part, without the express prior written consent of Safari.

### ISSUE THREAD

**Issue by 72897398163938615** [lorenzodifuccia/safaribooks#123]
The site, and all content and other elements available on or through the site, are the property of Safari and/or its content providers, and are protected by the laws of the United States and other countries, including their copyright and trademark laws. Your use of the site does not transfer to you any ownership or other rights in the site or its content. The site may not be copied, reproduced, republished, uploaded, transmitted, modified, indexed, catalogued, mirrored or distributed in any way, in whole or in part, without the express prior written consent of Safari.

**Comment by 72897398163938615** [comment]
The site, and all content and other elements available on or through the site, are the property of Safari and/or its content providers, and are protected by the laws of the United States and other countries, including their copyright and trademark laws. Your use of the site does not transfer to you any ownership or other rights in the site or its content. The site may not be copied, reproduced, republished, uploaded, transmitted, modified, indexed, catalogued, mirrored or distributed in any way, in whole or in part, without the express prior written consent of Safari.

**Comment by lorenzodifuccia** [comment]
#27
