### ISSUE TITLE
Please HELP!!! I cannot run safaribooks.

### ISSUE THREAD

**Issue by flxlocle** [lorenzodifuccia/safaribooks#124]
Here is a picture of the issue, I did install Python and Pip, and I did follow the direction, but I do not why this is happening. Please help. Thank you for your work.
![Capture](https://user-images.githubusercontent.com/53885793/62669975-8ff8f500-b95f-11e9-8919-d59ac890d531.PNG)

**Comment by kleyu** [comment]
@flxlocle please refer to: https://github.com/lorenzodifuccia/safaribooks/issues/115#issuecomment-516397299

**Comment by flxlocle** [comment]
Do you know how to retrieve a list of book ID's from OReilly's online book like in this project [https://github.com/raleighlittles/OReilly_Book_ID_Parser.git](url)?

The list that I want to retrieve is:
[https://www.oreilly.com/search/?query=&extended_publisher_data=true&highlight=true&include_assessments=false&include_case_studies=true&include_courses=true&include_orioles=true&include_playlists=true&include_collections=false&include_notebooks=false&is_academic_institution_account=false&formats=book&sort=publication_date&facet_json=true&page=0](url)

**Comment by varta2014** [comment]
please my friend i have same error
help please and show me by image how can fix and add this !!!!thank you!!
temporary fix change 73 line to:
        sys.stdout.write("\r" + put + "\n")
