### ISSUE TITLE
How to retrieve O’Reilly Book IDs

### ISSUE THREAD

**Issue by flxlocle** [lorenzodifuccia/safaribooks#126]
Do you know how to retrieve a list of book ID's from OReilly's online book like in this project https://github.com/raleighlittles/OReilly_Book_ID_Parser.git?

The list that I want to retrieve is:
https://www.oreilly.com/search/?query=&extended_publisher_data=true&highlight=true&include_assessments=false&include_case_studies=true&include_courses=true&include_orioles=true&include_playlists=true&include_collections=false&include_notebooks=false&is_academic_institution_account=false&formats=book&sort=publication_date&facet_json=true&page=0

**Comment by graffic** [comment]
From the readme:

> The ID is the digits that you find in the URL of the book description page:
https://www.safaribooksonline.com/library/view/book-name/XXXXXXXXXXXXX/
Like: https://www.safaribooksonline.com/library/view/test-driven-development-with/9781491958698/

**Comment by flxlocle** [comment]
I want to download all 40000 books

**Comment by zerodayz1** [comment]
Please let us know if you ever figure this out. Would love to be able to grab a bunch of books in this way.
