### ISSUE TITLE
SSO broken?

### ISSUE THREAD

**Issue by hrpomrx** [lorenzodifuccia/safaribooks#128]
The cookies and/or authentication process seem to have changed recently, and now I get: 

[#] API: Out-of-Session (Authentication credentials were not provided.).

Anyone else?

**Comment by okovwvrv** [comment]
Yes no longer works. Was raised in the original threads a while ago.

**Comment by hattaagung** [comment]
[#] API: Out-of-Session (Authentication credentials were not provided.).

same problem..any update ?

**Comment by C45tr0** [comment]
It works for me. Just had to also apply #102 to make it work though.

**Comment by hattaagung** [comment]
> It works for me. Just had to also apply #102 to make it work though.

actually, it worked on 2 weeks ago, but now it is error Out-of-Session. Do it work now ?

**Comment by hrpomrx** [comment]
I also applied #102 and it _appears_ to work until the very end of the book d/l at which point I get "error Out-of-Session" as @hattaagung mentioned. That was a big book though. I'll try some different book sizes.

**Comment by hrpomrx** [comment]
After some tooling around with #102 on a fresh clone... it seems to work - but maybe not every time, idk. The first time it failed with Out-of-Session, but then it worked for 2 books using the exact same cookies.json.

**Comment by LiuKay** [comment]
> After some tooling around with #102 on a fresh clone... it seems to work - but maybe not every time, idk. The first time it failed with Out-of-Session, but then it worked for 2 books using the exact same cookies.json.

I've tried serval days but still doesn't work. What are the possible reasons may cause this? Is there some workaround? Thanks a lot.

**Comment by okovwvrv** [comment]
I applied 102 back in June to even get started. SSO still not working. However this is closed. All I get is API Out of Session still.

**Comment by okovwvrv** [comment]
Check your cookies in a browser. You will see that you have cookies that are no longer possible to be exported automatically being set from safari. httponly cookies.
