### ISSUE TITLE
Entire chapters truncated

### ISSUE THREAD

**Issue by madchap** [lorenzodifuccia/safaribooks#129]
Hi,

I am experiencing entire chapters being truncated. However, no error appears when running the tool.

Unsure if this relates to #103 .

**Comment by ginkel** [comment]
From what I can see the truncated chapter appears as if one isn't logged in, i.e., is just the chapter preview.

**Comment by madchap** [comment]
Seems exactly like that, yes.

**Comment by kyledev80020** [comment]
I'm having exact same issues.  Some chapters download perfectly, others are obviously trial mode where they will trail off with a ..., others are entirely blank.  

But still most of the chapters come thru perfectly!  And I am using valid credentials.

**Comment by gleocadie** [comment]
Yep, I had the same issue.
I investigated and found that by avoiding updating the 'sessionid' in the cookie attribute fix the problem.
So replacing the method/function `update_cookies` by
```
    def update_cookies(self, jar):
        for cookie in jar:
            if cookie.name != 'sessionid':
                self.cookies.update({
                    cookie.name: cookie.value
                })
```

fixed the issue.
Having the `sessionid` updating after each request prevents the retrieval of other pages/chapters/section to be done correctly.

**Comment by gleocadie** [comment]
Yep, I had the same issue.
I investigated and found that by avoiding updating the 'sessionid' in the cookie attribute fixed the problem.
So replacing the method/function `update_cookies` by
```
    def update_cookies(self, jar):
        for cookie in jar:
            if cookie.name != 'sessionid':
                self.cookies.update({
                    cookie.name: cookie.value
                })
```

fixed the issue.
Having the `sessionid` updating after each request prevents the retrieval of other pages/chapters/section to be done correctly.

**Comment by madchap** [comment]
Works nicely, you should do a PR :)

**Comment by gleocadie** [comment]
yep, I'm  planning to to it (just testing it a little bit more) ;)
