### ISSUE TITLE
Regenerate epub without downloading again

### ISSUE THREAD

**Issue by amaltson** [lorenzodifuccia/safaribooks#132]
Add a flag to allow regenerating the EPUB without downloading all the content again and logging into Safari. This would be especially useful for contributors making patches as it provides a faster feedback loop.

**Comment by zedebugger** [comment]
Yes, would be very welcome.
Some images are just way too big for comfort, and one might want to do some imagemagick on the png:s to optimize them and then regenerate the epub.

**Comment by lorenzodifuccia** [comment]
An EPUB is a ZIP archive, try to use the snippet of code that build the zip file from `safaribooks.py`.
