### ISSUE TITLE
Argparse allow_abbrev problem

### ISSUE THREAD

**Issue by kovacsbalu** [lorenzodifuccia/safaribooks#14]
Probably I have old argparse in my ubuntu 14.04. But except this it works.
```
Traceback (most recent call last):
  File "safaribooks.py", line 965, in <module>
    allow_abbrev=False)
TypeError: __init__() got an unexpected keyword argument 'allow_abbrev'
```

**Comment by lorenzodifuccia** [comment]
Hi,
from the office `argparse`'s documentation:
> Changed in version 3.5: allow_abbrev parameter was added.

Update your Python 3!
