### ISSUE TITLE
some epub cannot be opened by win10 Edge

### ISSUE THREAD

**Issue by robertluwang** [lorenzodifuccia/safaribooks#141]
Some new generated epub not opened by Win10 Edge.

Found large number of errors when loaded to Sigil:

The OPF manifest contains duplicate ids for: img_ch05_images - A temporary id has been assigned to load this EPUB. You should edit your OPF file to remove the duplication.

As remedy, convert suspected epub to epub in latest Calibre, issue fixed then can be opened by Win10 Edge.

Would be good to fix epub format issue inside python script.

**Comment by lorenzodifuccia** [comment]
Try to convert the generated ebook into a new ebook using Calibre.
