### ISSUE TITLE
Can't log in anymore

### ISSUE THREAD

**Issue by richardxy** [lorenzodifuccia/safaribooks#144]
Hi,
I believe Safaribooksonline went through some changes, especially the login part. The downloader can't sign in any more. 

I got the issue:

> Login: no CSRF Token found in the page. Unable to continue the login. Try again...

If you can take a look, that'd be greatly appreciated!

Richard

**Comment by varta2014** [comment]
yes i have same error

> [-] Logging into Safari Books Online...
[#] Login: unable to perform auth login to Safari Books Online.
[*] Details:
    Unexpected error!
[+] Please delete all the `<BOOK NAME>/OEBPS/*.xhtml` files and restart the program.
[!] Aborting...

**Comment by lorenzodifuccia** [comment]
# For the GitHub community
Try to fix the login!
Submit a valid PR and I'll merge it within two day.
No old PRs, only new ones that start from the last commit.
Code must be stable.

**Comment by twiechert** [comment]
Works flawlessly here...

**Comment by lorenzodifuccia** [comment]
Closed with 31d7c9.
Thanks for the support.

**Comment by richardxy** [comment]
Thank you! Works now!
