### ISSUE TITLE
Authentication using SSO

### ISSUE THREAD

**Issue by sinedied** [lorenzodifuccia/safaribooks#148]
I have a SO account using my company (so no personal email/password) and as such I cannot use this program.
Is there a way to bypass the cred login, as I can directly access the website through company SSO using the VPN, without having to log in?
Thanks

**Comment by vikdean** [comment]
First use the --login method then enter the credentials. You will get a login error, then use the cookies way:
Login via Web, hit F12 in Firefox, and copy this to the console:var output = `{};document.cookie.split(/\s*;\s*/).forEach(function(pair) {pair = pair.split(/\s*=\s*/);output[pair[0]] = pair.splice(1).join('=');});console.log(JSON.stringify(output));`
Copy the output and insert it into a file called `cookies.json`; place that file into the folder of the downloader again and start it without the --login this time. It should work.

**Comment by MrEx88** [comment]
@vikdean , I tried you suggestion but it did not work for me. But I am not sure what you meant by "place `cookies.json` into the folder of the **downloader**". Can having a different SO cause this issue??

**Comment by vikdean** [comment]
> @vikdean , I tried you suggestion but it did not work for me. But I am not sure what you meant by "place `cookies.json` into the folder of the **downloader**". Can having a different SO cause this issue??
> 
> The error I am getting is an invalid credentials issue. I tried a couple times just in case I typed in my email and password wrong.

Your SSO username and password wont work, because normally you are typing those in through your own company's system when SafariBooks asks for it, right?

Place the `cookies.json` file into the folder you are running the `safaribooks.py` script from. Be aware, when I ran the script, sometimes it deleted the `cookies.json` file, sometimes it didn't...

**Comment by lucianf** [comment]
Incidentally I was trying this last night, I couldn't get this approach to work with the main project (`cookies.json` would always get deleted when I ran the script without `--login`); however, using [zqlu's feat-oauth branch](https://github.com/zqlu/safaribooks/tree/feat-oauth) it works really well.

**Comment by vikdean** [comment]
Yes, that's why first you have to run it with `--login` then without and the `cookies.json` created...

**Comment by jflattery** [comment]
So perhaps I'm doing this wrong. What should I use as my login email and password when using `--login`? I have been using the email address I use to login to my organization SSO with and random gibberish for the password. Than when I run it again after saving my `cookies.json` to the folder, the file gets deleted and I get `API: Out-of-Session (Authentication credentials were not provided.).` I have tried this several times without luck.

**Comment by lucianf** [comment]
> So perhaps I'm doing this wrong.

Have you tried what I suggested earlier? It worked fine for me using the other repo branch. Skip the `login` part and just use the `cookies.json` you get from the browser after having logged on with the SSO.

**Comment by TheMkrage** [comment]
Hi! 
I am attempting to do this and have attempted following @vikdean's instructions on both master and [zqlu's feat-oauth branch](https://github.com/zqlu/safaribooks/tree/feat-oauth). On the master branch, I am getting: 
`[#] Authentication issue: unable to access profile page.                        
[!] Aborting...  `
And on the feat-oauth branch I am getting: 
`[#] API: Out-of-Session (Authentication credentials were not provided.). `

 It looks like it auths but fails to get to the profile page. I can provide whatever info needed to help, thanks!
