### ISSUE TITLE
book text not dark enough 

### ISSUE THREAD

**Issue by hassanaboueldahab** [lorenzodifuccia/safaribooks#159]
just the book index with chapters name is dark black colour but the rest of the book little lighter, it's very annoying when you read using kindle device

**Comment by hassanaboueldahab** [comment]
<img width="408" alt="Screen Shot 2019-11-26 at 10 50 48 PM" src="https://user-images.githubusercontent.com/30595394/69671701-40ba0a00-109f-11ea-810d-0ad3362eea36.png">
<img width="384" alt="Screen Shot 2019-11-26 at 10 50 51 PM" src="https://user-images.githubusercontent.com/30595394/69671702-4152a080-109f-11ea-9d1c-148d49465f8c.png">
you could see the diffrence

**Comment by georgebastille** [comment]
I noticed this or something similar in several books. After a reference link, the font for the rest of the paragraph is lighter. It appear the font colour change for the link is not closed, and carries over to the body text. This is then reset by a new <p> tag (working theory, I have not looked at the code yet).

**Comment by rhm-fyayc** [comment]
@hassanaboueldahab as a workaround you can tweak the css at calibre

**Comment by 9beach** [comment]
When you install calibre, `ebook-convert` cli is also installed. Try `ebook-convert book.epub book.azw3 --extra-css 'body, h1, h2, h3, h4, div, p {  color: black !important; }'`.

**Comment by ivan-ha** [comment]
in addition to @9beach's answer, you can also put the extra css to calibre UI under `Look & feel -> Styling`

![Screenshot 2020-01-09 at 18 37 13](https://user-images.githubusercontent.com/20895743/72060512-16e73a80-330f-11ea-977b-b1994fd5a043.png)

**Comment by obar1** [comment]
is there any piece in the code to do that when downloading guys
