### ISSUE TITLE
make script run on android by removing dependency from multiprocessing module

### ISSUE THREAD

**Issue by ghistes** [lorenzodifuccia/safaribooks#161]
Hi,

this may be too much to ask for, but I would like to run the script on my android-tablet and currently that does not work.

I use a chrooted debian-environment on top of termux that provides a linux-like environment on android where I can run many perl as well as python-scripts.

Now I can install all dependencies for the safaribooks-scripts and it compiles ok, but at runtime there is a problem with the multiprocessing module: It depends on /dev/shm which is not availabe in this environment, resulting in an exception.

I've had a very cursory look at the code and it seems to be that the script does not use that much functionality from multiprocessing (mainly a work-queue-implementation) and I was wondering that maybe it would be possible to remove this dependency and make the script run on the tablet where the resulting epubs will be consumed, as that would be extremely cool (at least for me).

So could you please consider it?

Many thanks!

**Comment by lorenzodifuccia** [comment]
Please, if you consider it useful, create a PR.

Meanwhile, you can change the behaviour of the script in order to let it think you are in a Windows environment and do not use `multiprocessing`:

```python
...
from urllib.parse import urljoin, urlparse, parse_qs, quote_plus

# Add following line
sys.platform = "windows"

PATH = os.path.dirname(os.path.realpath(__file__))
...
```

**Comment by mrlovat** [comment]
I tried the proposed workaround but it still doesn't work hitting this wall https://github.com/termux/termux-app/issues/1272
