### ISSUE TITLE
Partial content download

### ISSUE THREAD

**Issue by crixo** [lorenzodifuccia/safaribooks#168]
Sections/chapters with multipage content are partially downloaded so the book is incomplete. The text get suddenly truncated adding tre dots and the next page contains the next chapter

**Comment by artemstorozhuk** [comment]
https://github.com/lorenzodifuccia/safaribooks/issues/103
https://github.com/lorenzodifuccia/safaribooks/issues/150

**Comment by crixo** [comment]
Pulling the latest version solved my issue. Thanks for the hint

**Comment by artemstorozhuk** [comment]
Interesting, because I have an ellipsis (truncated content). Probably connected with SSO auth.

**Comment by crixo** [comment]
I check the issues I had w/ few books and now they have been solved. I'll keep you posted in case of new issues.
