### ISSUE TITLE
Authentication issue unable to access profile page

### ISSUE THREAD

**Issue by hoangphuc2019** [lorenzodifuccia/safaribooks#178]
They changed URL Login.

[12/Jan/2020 11:15:25] ** Welcome to SafariBooks! **
[12/Jan/2020 11:15:27] Authentication issue: unable to access profile page.
[12/Jan/2020 11:15:27] Last request done:
        URL: https://learning.oreilly.com/accounts/login/?next=/profile/
        DATA: None
        OTHERS: {}

        302
        Server: openresty/1.15.8.2
        Content-Type: text/html; charset=utf-8
        Content-Language: en-US
        Cache-Control: max-age=0
        X-Frame-Options: SAMEORIGIN
        x-content-type-options: nosniff
        Expires: Sun, 12 Jan 2020 04:15:27 GMT
        Location: /login/unified/?next=/profile/
        x-xss-protection: 1; mode=block
        strict-transport-security: "max-age=31536000; includeSubDomains"
        Set-Cookie: messages=; expires=Thu, 01-Jan-1970 00:00:00 GMT; Max-Age=0; Path=/, logged_in=; Domain=.oreilly.com; expires=Thu, 01-Jan-1970 00:00:00 GMT; Max-Age=0; Path=/, sessionid=xxxxxxxxq7gclti2b59j17bnxxxxxxxx; expires=Sun, 26-Jan-2020 04:15:27 GMT; Max-Age=1209600; Path=/; secure, api_key=; expires=Thu, 01-Jan-1970 00:00:00 GMT; Max-Age=0; Path=/
        Accept-Ranges: bytes, bytes
        Content-Length: 0
        Date: Sun, 12 Jan 2020 04:15:27 GMT
        Via: 1.1 varnish
        Connection: keep-alive
        X-Client-IP: xx.xx.xx.xx
        X-Served-By: cache-hkg17922-HKG
        X-Cache: MISS
        X-Cache-Hits: 0
        X-Timer: S1578802527.625681,VS0,VE604
        Vary: Accept-Language, Authorization, Cookie, Origin

**Comment by tomvanoppens** [comment]
to fix change to the following
`PROFILE_URL = SAFARI_BASE_URL + "/home/?next=%2Fprofile%2F"`

**Comment by kastoestoramadus** [comment]
now:
```
[12/Jan/2020 17:36:20] Last request done:
        URL: https://learning.oreilly.com/home/?next=%2Fprofile%2F
        DATA: None
        OTHERS: {}

        307
        server: istio-envoy
        cache-control: max-age=0
        content-type: text/html; charset=utf-8
        location: /accounts/login-academic-check/?next=%2Fhome%2F%3Fnext%3D%252Fprofile%252F
        x-envoy-upstream-service-time: 116
        x-powered-by: Express
        Accept-Ranges: bytes, bytes
        Content-Length: 205
        Date: Sun, 12 Jan 2020 16:36:19 GMT
        Via: 1.1 varnish
        Connection: keep-alive
        X-Client-IP: 185.102.188.221
        X-Served-By: cache-hhn4022-HHN
        X-Cache: MISS
        X-Cache-Hits: 0
        X-Timer: S1578846979.805608,VS0,VE266
        Vary: Accept,Accept, Accept-Encoding, Authorization, `Cookie```
```

**Comment by kastoestoramadus** [comment]
pages are incomplete:
![obraz](https://user-images.githubusercontent.com/6271645/72222540-244a3200-3566-11ea-85b3-da24de54d6e8.png)
below ... should be much more

**Comment by hoangphuc2019** [comment]
It was not work.
**LOG**
[13/Jan/2020 09:27:16] ** Welcome to SafariBooks! **
[13/Jan/2020 09:27:17] Authentication issue: unable to access profile page.
[13/Jan/2020 09:27:17] Last request done:
        URL: https://learning.oreilly.com/home/?next=%2Fprofile%2F
        DATA: None
        OTHERS: {}

        307
        server: istio-envoy
        cache-control: max-age=0
        content-type: text/plain; charset=utf-8
        location: /accounts/login-academic-check/?next=%2Fhome%2F%3Fnext%3D%252Fprofile%252F
        x-envoy-upstream-service-time: 142
        x-powered-by: Express
        Accept-Ranges: bytes, bytes
        Content-Length: 109
        Date: Mon, 13 Jan 2020 02:27:16 GMT
        Via: 1.1 varnish
        Connection: keep-alive
        X-Client-IP: xx.xx.xx.xx
        X-Served-By: cache-hkg17926-HKG
        X-Cache: MISS
        X-Cache-Hits: 0
        X-Timer: S1578882437.696496,VS0,VE285
        Vary: Accept,Accept, Accept-Encoding, Authorization, Cookie

Temporary Redirect. Redirecting to /accounts/login-academic-check/?next=%2Fhome%2F%3Fnext%3D%252Fprofile%252F

**Comment by kastoestoramadus** [comment]
@hoangphuc2019 Are you sure you've entered the profile page to get the cookies? I had the same error.

**Comment by hoangphuc2019** [comment]
> @hoangphuc2019 Are you sure you've entered the profile page to get the cookies? I had the same error.

yeap, I was using cookies to download instead of login option.  If using login option, it works fine and no need to change anything.
