### ISSUE TITLE
Profile URL changed

### ISSUE THREAD

**Issue by tomvanoppens** [lorenzodifuccia/safaribooks#179]
In my case, I've changed this:

PROFILE_URL = SAFARI_BASE_URL + "/home/?next=%2Fprofile%2F"

and it's working fine!

Regards!

_Originally posted by @lurumad in https://github.com/lorenzodifuccia/safaribooks/issues/2#issuecomment-567912638_

**Comment by tomvanoppens** [comment]
dupe of #178

**Comment by beni0888** [comment]
@tomvanoppens I see your change is still not in master branch. Have you considered filing a PR?

**Comment by tomvanoppens** [comment]
I have , but I can't validate if it works with non SSO accounts
