### ISSUE TITLE
ModuleNotFoundErro

### ISSUE THREAD

**Issue by TarekMansour** [lorenzodifuccia/safaribooks#181]
File "safaribooks.py", line 11, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by elobire** [comment]
Have you followed the setup instructions and run 
`pip3 install -r requirements.txt
`

**Comment by TarekMansour** [comment]
yes I did it.
But today, I used "python safaribooks.py" instead of "python**3** safaribooks.py" and it works

**Comment by d3xt3r2909** [comment]
`pip3 install requests` just install specific module and it will work
