### ISSUE TITLE
New to python, would like to be able to get this running

### ISSUE THREAD

**Issue by Sgrapes** [lorenzodifuccia/safaribooks#182]
$ git clone https://github.com/lorenzodifuccia/safaribooks.git
Cloning into 'safaribooks'...

$ cd safaribooks/
$ pip3 install -r requirements.txt

lxml>=4.1.1
requests>=2.20.0

$ python3 safaribooks.py --cred "account_mail@mail.com:password01" XXXXXXXXXXXXX

import re
import os
import sys
import json
import shutil
import getpass
import logging
import argparse
import requests
import traceback
from html import escape
from random import random
from lxml import html, etree
from multiprocessing import Process, Queue, Value
from urllib.parse import urljoin, urlparse, parse_qs, quote_plus

This is how it looks like in Sublime Text except that I obviously have my email, password and book ID in there. Would really like to be able to get this running and know what I'm doing wrong!
Thank you

**Comment by scottcow** [comment]
Input each $ line one by one into Bash

The only change I had to make to get it working was to remove the '3' from 'python3'. Double check what the actual name of your Python executable is. 

Don't know if this will help. I am new to Python myself
