### ISSUE TITLE
unable to convert from epub to mobi format

### ISSUE THREAD

**Issue by shashikumaarb** [lorenzodifuccia/safaribooks#183]
Ignoring CSS rule with invalid selector: u'input#id_username:-ms-input-placeholder' (The pseudo-class :-ms-input-placeholder is not supported)
Ignoring CSS rule with invalid selector: u'input#id_username::-moz-placeholder' (The pseudo-class :-moz-placeholder is not supported)
Ignoring CSS rule with invalid selector: u'input#id_username::-webkit-input-placeholder' (The pseudo-class :-webkit-input-placeholder is not supported)
Ignoring CSS rule with invalid selector: u'body.night-mode #sbo-rt-content .annotator-wrapper ::selection' (The pseudo-class :selection is not supported)
Ignoring CSS rule with invalid selector: u'body.night-mode #sbo-rt-content .annotator-wrapper ::-moz-selection' (The pseudo-class :-moz-selection is not supported)
PropertyValue: Missing token for production Choice(ColorValue, Dimension, URIValue, Value, variable, MSValue, CSSCalc, function): (u'CHAR', u'<', 1, 70)
No content to parse.
PropertyValue: Unknown syntax or no value:  <%= font_size %> 
CSSStyleDeclaration: Syntax Error in Property: font-size: <%= font_size %> !important
PropertyValue: Missing token for production Choice(ColorValue, Dimension, URIValue, Value, variable, MSValue, CSSCalc, function): (u'CHAR', u'<', 1, 72)
No content to parse.
PropertyValue: Unknown syntax or no value:  <%= font_family %> 
CSSStyleDeclaration: Syntax Error in Property: font-family: <%= font_family %> !important
PropertyValue: Missing token for production Choice(ColorValue, Dimension, URIValue, Value, variable, MSValue, CSSCalc, function): (u'CHAR', u'<', 1, 30)
No content to parse.
PropertyValue: Unknown syntax or no value:  <%= column_width %>% 
CSSStyleDeclaration: Syntax Error in Property: max-width: <%= column_width %>% !important

Ignoring CSS rule with invalid selector: u'input:read-only' (The pseudo-class :read-only is not supported)
Ignoring CSS rule with invalid selector: u'button::-moz-focus-inner' (The pseudo-class :-moz-focus-inner is not supported)
Ignoring CSS rule with invalid selector: u'.searchbox .search-query:focus::-webkit-input-placeholder' (The pseudo-class :-webkit-input-placeholder is not supported)
Ignoring CSS rule with invalid selector: u'.wrap-search-form .search-query:focus::-webkit-input-placeholder' (The pseudo-class :-webkit-input-placeholder is not supported)
Ignoring CSS rule with invalid selector: u'.searchbox select.search-params::-ms-expand' (The pseudo-class :-ms-expand is not supported)
Ignoring CSS rule with invalid selector: u'.wrap-search-form select.search-params::-ms-expand' (The pseudo-class :-ms-expand is not supported)
Ignoring CSS rule with invalid selector: u'.sbo-inpage-toc .tabs li::selection' (The pseudo-class :selection is not supported)
Ignoring CSS rule with invalid selector: u'#id_username:-moz-placeholder' (The pseudo-class :-moz-placeholder is not supported)
Ignoring CSS rule with invalid selector: u'#id_username:-ms-input-placeholder' (The pseudo-class :-ms-input-placeholder is not supported)
Ignoring CSS rule with invalid selector: u'#id_username::-webkit-input-placeholder' (The pseudo-class :-webkit-input-placeholder is not supported)
Ignoring CSS rule with invalid selector: u'#id_username::-moz-placeholder' (The pseudo-class :-moz-placeholder is not supported)
Ignoring CSS rule with invalid selector: u'input#id_username:-ms-input-placeholder' (The pseudo-class :-ms-input-placeholder is not supported)
Ignoring CSS rule with invalid selector: u'input#id_username::-moz-placeholder' (The pseudo-class :-moz-placeholder is not supported)
Ignoring CSS rule with invalid selector: u'input#id_username::-webkit-input-placeholder' (The pseudo-class :-webkit-input-placeholder is not supported)

Ignoring CSS rule with invalid selector: u'body.night-mode #sbo-rt-content .annotator-wrapper ::selection' (The pseudo-class :selection is not supported)
Ignoring CSS rule with invalid selector: u'body.night-mode #sbo-rt-content .annotator-wrapper ::-moz-selection' (The pseudo-class :-moz-selection is not supported)
PropertyValue: Missing token for production Choice(ColorValue, Dimension, URIValue, Value, variable, MSValue, CSSCalc, function): (u'CHAR', u'<', 1, 70)
No content to parse.
PropertyValue: Unknown syntax or no value:  <%= font_size %> 
CSSStyleDeclaration: Syntax Error in Property: font-size: <%= font_size %> !important
PropertyValue: Missing token for production Choice(ColorValue, Dimension, URIValue, Value, variable, MSValue, CSSCalc, function): (u'CHAR', u'<', 1, 72)
No content to parse.
PropertyValue: Unknown syntax or no value:  <%= font_family %> 
CSSStyleDeclaration: Syntax Error in Property: font-family: <%= font_family %> !important
PropertyValue: Missing token for production Choice(ColorValue, Dimension, URIValue, Value, variable, MSValue, CSSCalc, function): (u'CHAR', u'<', 1, 30)
No content to parse.
PropertyValue: Unknown syntax or no value:  <%= column_width %>% 
CSSStyleDeclaration: Syntax Error in Property: max-width: <%= column_width %>% !important

Ignoring CSS rule with invalid selector: u'input:read-only' (The pseudo-class :read-only is not supported)
Ignoring CSS rule with invalid selector: u'button::-moz-focus-inner' (The pseudo-class :-moz-focus-inner is not supported)
Ignoring CSS rule with invalid selector: u'.searchbox .search-query:focus::-webkit-input-placeholder' (The pseudo-class :-webkit-input-placeholder is not supported)
Ignoring CSS rule with invalid selector: u'.wrap-search-form .search-query:focus::-webkit-input-placeholder' (The pseudo-class :-webkit-input-placeholder is not supported)
Ignoring CSS rule with invalid selector: u'.searchbox select.search-params::-ms-expand' (The pseudo-class :-ms-expand is not supported)
Ignoring CSS rule with invalid selector: u'.wrap-search-form select.search-params::-ms-expand' (The pseudo-class :-ms-expand is not supported)
Ignoring CSS rule with invalid selector: u'.sbo-inpage-toc .tabs li::selection' (The pseudo-class :selection is not supported)
Ignoring CSS rule with invalid selector: u'#id_username:-moz-placeholder' (The pseudo-class :-moz-placeholder is not supported)
Ignoring CSS rule with invalid selector: u'#id_username:-ms-input-placeholder' (The pseudo-class :-ms-input-placeholder is not supported)
Ignoring CSS rule with invalid selector: u'#id_username::-webkit-input-placeholder' (The pseudo-class :-webkit-input-placeholder is not supported)
Ignoring CSS rule with invalid selector: u'#id_username::-moz-placeholder' (The pseudo-class :-moz-placeholder is not supported)
Ignoring CSS rule with invalid selector: u'input#id_username:-ms-input-placeholder' (The pseudo-class :-ms-input-placeholder is not supported)
Ignoring CSS rule with invalid selector: u'input#id_username::-moz-placeholder' (The pseudo-class :-moz-placeholder is not supported)
Ignoring CSS rule with invalid selector: u'input#id_username::-webkit-input-placeholder' (The pseudo-class :-webkit-input-placeholder is not supported)
Ignoring CSS rule with invalid selector: u'body.night-mode #sbo-rt-content .annotator-wrapper ::selection' (The pseudo-class :selection is not supported)
Ignoring CSS rule with invalid selector: u'body.night-mode #sbo-rt-content .annotator-wrapper ::-moz-selection' (The pseudo-class :-moz-selection is not supported)
PropertyValue: Missing token for production Choice(ColorValue, Dimension, URIValue, Value, variable, MSValue, CSSCalc, function): (u'CHAR', u'<', 1, 70)
No content to parse.
PropertyValue: Unknown syntax or no value:  <%= font_size %> 
CSSStyleDeclaration: Syntax Error in Property: font-size: <%= font_size %> !important
PropertyValue: Missing token for production Choice(ColorValue, Dimension, URIValue, Value, variable, MSValue, CSSCalc, function): (u'CHAR', u'<', 1, 72)
No content to parse.
PropertyValue: Unknown syntax or no value:  <%= font_family %> 
CSSStyleDeclaration: Syntax Error in Property: font-family: <%= font_family %> !important
PropertyValue: Missing token for production Choice(ColorValue, Dimension, URIValue, Value, variable, MSValue, CSSCalc, function): (u'CHAR', u'<', 1, 30)
No content to parse.
PropertyValue: Unknown syntax or no value:  <%= column_width %>% 
CSSStyleDeclaration: Syntax Error in Property: max-width: <%= column_width %>% !important

**Comment by lorenzodifuccia** [comment]
Those are only warnings, Calibre will fix them.
