### ISSUE TITLE
Incomplete dowloads

### ISSUE THREAD

**Issue by kastoestoramadus** [lorenzodifuccia/safaribooks#184]
Hello Loren,

The download completes without any issues, there is no error in the log file.
But the downloaded file content is not complete.
tried with 0131482394

pages end with ...

Could you please look into it.

**Comment by obar1** [comment]
look other fork... they works better

**Comment by TheSnoozer** [comment]
> look other fork... they works better

which one? examples?

**Comment by noxymon** [comment]
> > look other fork... they works better
> 
> which one? examples?

i found this fork : https://github.com/tpiechaczek/safaribooks
work better.

**Comment by eldarkt** [comment]
same here, incomplete downloads, tpiechaczek fork gives an error "Authentication issue: unable to access profile page" for sso login.

**Comment by eldarkt** [comment]
it looks like they changed cookies format.
Can anyone please post a new format, because [this ](https://github.com/lorenzodifuccia/safaribooks/issues/2)one doesn't work anymore?
Thanks!

**Comment by ishida330** [comment]
Thanks , with changing "web_url" -> "content" at 811, now I can get complete texts. Great !
But it seems we've lost CSSs,  so no formatting done at EPUB generation.( Yet still, better than incomplete contents , of course)

![NEW vs OLD](https://user-images.githubusercontent.com/9675895/76586682-ef863700-6524-11ea-9139-0ecb875eb33d.PNG)
