### ISSUE TITLE
API: Out-of-Session

### ISSUE THREAD

**Issue by hugodneto** [lorenzodifuccia/safaribooks#185]
Anyone with problem about API: Out-of-Session ?

Example:
python safaribooks.py --cred "hxxxx@xxxxx.com.:XXXXXXX" 9780738457635
[-] Logging into Safari Books Online...
[-] Successfully authenticated.
[*] Retrieving book info...
[#] API: Out-of-Session (You do not have permission to perform this action.).
[!] Aborting...

**Comment by Simonig** [comment]
You should start the free trial subscription for your oreilly account before.
