### ISSUE TITLE
Unhandled Exception: 'int' object has no attribute 'iter_content'

### ISSUE THREAD

**Issue by kienvn** [lorenzodifuccia/safaribooks#187]
It happen when i download  9780135447260

**Comment by acrofales** [comment]
This also happened to me for book 9780124166028

It didn't happen before I applied the change from:
https://github.com/lorenzodifuccia/safaribooks/pull/188

However, without changing that snippet it had the behaviour described in issue https://github.com/lorenzodifuccia/safaribooks/issues/184

Nevertheless after changing this snippet, it does not correctly download the cover page and images (but it does download the actual book content correctly, which is much preferrable to the cover page being pretty).

**Comment by axelstram** [comment]
I have the same problem after applying #188. Does anybody know which changes need to be made so that it also downloads the missing images?

**Comment by TheSnoozer** [comment]
Both #188 and #184 had been merged into master. Can you get the latest version and try again?
