### ISSUE TITLE
Unhandled Exception: 'NoneType' object has no attribute 'replace' (type: AttributeError)

### ISSUE THREAD

**Issue by agentchromatic7** [lorenzodifuccia/safaribooks#191]
[info_9780135262726.log](https://github.com/lorenzodifuccia/safaribooks/files/4269886/info_9780135262726.log)

Please see attached log. I'm new to programming and python and i'm not sure how to fix this error. If someone could assist me or point me in the right direction, I'd greatly appreciate it. I'm not exactly sure what is going on or where to begin to fix the code if necessary.

**Comment by TheSnoozer** [comment]
Hi,
it seems that this is related to https://github.com/lorenzodifuccia/safaribooks/issues/171

See https://github.com/TheSnoozer/safaribooks/commit/3d3147a1ad1bb80c9e37d306f618054a0495fc50 how it could be fixed.

**Comment by agentchromatic7** [comment]
> Hi,
> it seems that this is related to #171
> 
> See [TheSnoozer@3d3147a](https://github.com/TheSnoozer/safaribooks/commit/3d3147a1ad1bb80c9e37d306f618054a0495fc50) how it could be fixed.

@TheSnoozer thanks! I replaced that line of code and it worked. I was able to pull it!
