### ISSUE TITLE
Traceback error, ImportError : No module

### ISSUE THREAD

**Issue by ds0987654321** [lorenzodifuccia/safaribooks#194]
$ python safaribooks.py --cred "xxx@gmail.com:xxx" 9781491958698
Traceback (most recent call last):
  File "safaribooks.py", line 13, in <module>
    from xhtml import escape
ImportError: No module named xhtml

When I try with python3 I get this error:-
bash: python3: command not found

**Comment by lorenzodifuccia** [comment]
README: only python3+
Please, install it...
