### ISSUE TITLE
CSS not found

### ISSUE THREAD

**Issue by jp-13** [lorenzodifuccia/safaribooks#196]
Hi, 
I tried the latest version of the script. 
I had to change one variable as the logon check was not working:  "PROFILE_URL = SAFARI_BASE_URL 
After that it works but it does not find anymore the CSS files: 
"[-] Downloading book CSSs... (0 files)"

**Comment by TheSnoozer** [comment]
I don't think this is necessarily a problem.
In general the [CSS-File-Lookup](https://github.com/lorenzodifuccia/safaribooks/blob/ba29ef43cf1365275f964447e973ff666c53d14c/safaribooks.py#L657) is searching for `stylesheet`-elements. When searching a downloaded `OEBPS` for stylesheet, style, or any external references I can't find any relevant.

I suspect that this might be related to this change:
https://github.com/lorenzodifuccia/safaribooks/commit/5b9961614a7d6bc954f54d4f653f6e1346c030c1


Do you see any display discrepancy? If so what is the book-id?

**Comment by jp-13** [comment]
I updated the safaribooks.py file here: #198

**Comment by lorenzodifuccia** [comment]
Hello,
@jp-13, @noxymon, @TheSnoozer, could you please test the last commit?
I updated the code with a functionality that takes the CSS from the JSON information about the book.
Let me know if it work.

**Comment by noxymon** [comment]
> Hello,
> @jp-13, @noxymon, @TheSnoozer, could you please test the last commit?
> I updated the code with a functionality that takes the CSS from the JSON information about the book.
> Let me know if it work.

Tested using 9781118238936 in master branch, CSS downloaded. 
but : 
- the images are not downloaded. try [this](https://github.com/lorenzodifuccia/safaribooks/pull/200/commits/0e599af4fbd07677f37be92f00066ac6cd9ab7ec).
- TOC linked also missing.  try [this](https://github.com/lorenzodifuccia/safaribooks/pull/200/commits/a7b707bcec70847cc3638b4521cc34c5b209cbe6),

**Comment by TheSnoozer** [comment]
Thanks @lorenzodifuccia for the fix! Works on my end - haven't noticed any issues.

As a side note - the following should be fixed now too:
- https://github.com/lorenzodifuccia/safaribooks/issues/206
- https://github.com/lorenzodifuccia/safaribooks/issues/201
- https://github.com/lorenzodifuccia/safaribooks/issues/174
- https://github.com/lorenzodifuccia/safaribooks/issues/163
