### ISSUE TITLE
SSO login

### ISSUE THREAD

**Issue by pteczar** [lorenzodifuccia/safaribooks#197]
Hey, is there a way to login with an SSO?

I just use my company email to access the safari books account.

Please let me know if this is available. 

Thank you! 

Best,
PT

**Comment by jp-13** [comment]
Yes, you need to create a cookies.json file.
For that you can run the following script (shared previously somewhere in the comments) in firefox console and past the result in the cookies.json file:
`var output = {};document.cookie.split(/\s*;\s*/).forEach(function(pair) {pair = pair.split(/\s*=\s*/);output[pair[0]] = pair.splice(1).join('=');});console.log(JSON.stringify(output));`

**Comment by antoineco** [comment]
See also this for detailed instructions (the command above is not enough): https://github.com/lorenzodifuccia/safaribooks/issues/2#issuecomment-591855132

**Comment by lorenzodifuccia** [comment]
Hello,
I updated the repo with new info and tools for SSO.
Take a look also at the README.
