### ISSUE TITLE
Cookies.json format

### ISSUE THREAD

**Issue by neogta** [lorenzodifuccia/safaribooks#2]
Hello, my safaribooksonline account is SSO handled by my company, thus I have NO password.
Could you post an example of the cookies.json format ? (with dummy values of course)

**Comment by lorenzodifuccia** [comment]
Sure!
This is an example of `cookies.json` file:
```javascript
{"sessionid": "28cb00fc5fefca1c33677383b7c2499f", "salesforce_id": "c22b5131a048c89949719ddfc77a9401", "csrfsafari": "NAowChgKB1Nwb3RpZnkSABoGmAEByAEB", "original_referer": "\"https://www.safaribooksonline.com/home/\"", "BrowserCookie": "c6691600-bbf6-4c96-b721-af081ff879d8", "corp_sessionid": "f2be05e433a0e5883920f34bcf3ce83a", "logged_in": "y"}
```
:+1:

**Comment by neogta** [comment]
Thank you !

**Comment by neogta** [comment]
(and it works ! ) (after setting "locale" to UTF8)

**Comment by lorenzodifuccia** [comment]
Perfect!! Thanks for the issue.

**Comment by gabrielgiordan** [comment]
Bookmarlet version of @anhhh11 script

javascript:(function(){var output = {};document.cookie.split(/\s*;\s*/).forEach(function(pair) {pair = pair.split(/\s*=\s*/);output[pair[0]]=pair.splice(1).join('=');});console.log(JSON.stringify(output));})();

**Comment by anhhh11** [comment]
Bookmarlet generate cookies.json

`javascript:(function(){var output={};document.cookie.split(/\s*;\s*/).forEach(function(pair){pair=pair.split(/\s*=\s*/);output[pair[0]]=pair.splice(1).join('=')});var a=window.document.createElement('a');a.href=window.URL.createObjectURL(new Blob([JSON.stringify(output)],{type:'text/json'}));a.download='cookies.json';document.body.appendChild(a);a.click();document.body.removeChild(a)})()`

**Comment by hbakhtiyor** [comment]
i tried, but nothing works
`[#] API: Out-of-Session (You do not have permission to perform this action.).`

**Comment by tdnghia98** [comment]
Hi how can I specify the cookies file in the command line?

**Comment by anhhh11** [comment]
@tdnghia98: Just copy cookies.json to the same folder as safaribooks.py an run this file.

**Comment by sathish316** [comment]
> (and it works ! ) (after setting "locale" to UTF8)

@neogta How or where do you set the locale?

**Comment by tomvanoppens** [comment]
> {"sessionid": "28cb00fc5fefca1c33677383b7c2499f", "salesforce_id": "c22b5131a048c89949719ddfc77a9401", "csrfsafari": "NAowChgKB1Nwb3RpZnkSABoGmAEByAEB", "original_referer": "\"https://www.safaribooksonline.com/home/\"", "BrowserCookie": "c6691600-bbf6-4c96-b721-af081ff879d8", "corp_sessionid": "f2be05e433a0e5883920f34bcf3ce83a", "logged_in": "y"}

seems you only need the sessionid

**Comment by ghnu** [comment]
> One fast way to get the cookie:
> Paste these code into Console of web inspector (F12) in firefox or chrome to get cookie, then paste into cookies.json
> `var output = {};document.cookie.split(/\s*;\s*/).forEach(function(pair) {pair = pair.split(/\s*=\s*/);output[pair[0]] = pair.splice(1).join('=');});console.log(JSON.stringify(output));`

That doesn't work for me. No matter what I try, I always get the error "undefinied" in the F12 console, and {"":""} as empty result. How to solve that?

**Comment by dkuzma2** [comment]
> > (and it works ! ) (after setting "locale" to UTF8)
> 
> @neogta How or where do you set the locale?

Either this is saving the JSON file with correct UTF-8 encoding or system locale - https://www.tecmint.com/set-system-locales-in-linux/

Do you get any errors?

**Comment by deppfx** [comment]
I am getting this error even after using [cookies.json](https://github.com/lorenzodifuccia/safaribooks/issues/2#issuecomment-429881744) 
```                                                                                                                                                                                          
~/git/safaribooks $ (master) python3 safaribooks.py --no-kindle 9781457185519
                                                                                                                                                                                                                   
 ██████╗     ██████╗ ██╗  ██╗   ██╗██████╗ 
██╔═══██╗    ██╔══██╗██║  ╚██╗ ██╔╝╚════██╗
██║   ██║    ██████╔╝██║   ╚████╔╝   ▄███╔╝
██║   ██║    ██╔══██╗██║    ╚██╔╝    ▀▀══╝ 
╚██████╔╝    ██║  ██║███████╗██║     ██╗   
 ╚═════╝     ╚═╝  ╚═╝╚══════╝╚═╝     ╚═╝                                           

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[#] Authentication issue: unable to access profile page.                                                                                                                                                           
[!] Aborting...
```

**Comment by dkuzma2** [comment]
@deppfx 

Make sure that the content of the cookie file looks properly.
What I did is manually edited the json file as I also had issues with exporting the cookie.

In the browser console run:
`var output = {};document.cookie.split(/\s*;\s*/).forEach(function(pair) {pair = pair.split(/\s*=\s*/);output[pair[0]] = pair.splice(1).join('=');});console.log(JSON.stringify(output));`
and then display the cookie in json by typing `output` and copy the content to the json file.

**Comment by antrianis** [comment]
does this still work? I get:
[#] Authentication issue: unable to access profile page.
[!] Aborting...

**Comment by lurumad** [comment]
Hi @antrianis 

Would you mind to tell us what url have you changed in the script?

Regards!

**Comment by antrianis** [comment]
diff --git a/safaribooks.py b/safaribooks.py
index 95c13a3..1ec707e 100644
--- a/safaribooks.py
+++ b/safaribooks.py
@@ -29,6 +29,7 @@ ORLY_BASE_URL = "https://www." + ORLY_BASE_HOST
 SAFARI_BASE_URL = "https://" + SAFARI_BASE_HOST
 API_ORIGIN_URL = "https://" + API_ORIGIN_HOST
 PROFILE_URL = SAFARI_BASE_URL + "/profile/"
+PROFILE_URL = "https://www.oreilly.com/member/"

I guess there are a few entry points for oreilly, and this is the one used
for me

**Comment by lurumad** [comment]
In my case, I've changed this:

PROFILE_URL = SAFARI_BASE_URL + "/home/?next=%2Fprofile%2F"

and it's working fine!

Regards!

**Comment by eldarkt** [comment]
it looks like they changed cookies format.
Can anyone please post a new format, because this one doesn't work anymore?
Thanks!

**Comment by deppfx** [comment]
This is what worked in Firefox.

1. As @dkuzma2 mentioned, In the browser console run:
`var output = {};document.cookie.split(/\s*;\s*/).forEach(function(pair) {pair = pair.split(/\s*=\s*/);output[pair[0]] = pair.splice(1).join('=');});console.log(JSON.stringify(output));`

2. Edit safaribooks.py and add a new line
`PROFILE_URL = "https://www.oreilly.com/member/"`
right below the line
`PROFILE_URL = SAFARI_BASE_URL + "/profile/"`

3. Run
`python3 safaribooks.py <BOOKID>`

**Comment by hasanloo** [comment]
After these steps I am getting the following error:

> [-] Successfully authenticated.
> [*] Retrieving book info...
> [#] API: Out-of-Session (Authentication credentials were not provided.).
> 
> [!] Aborting...

**Comment by uday-nandam** [comment]
> After these steps I am getting the following error:
> 
> > [-] Successfully authenticated.
> > [*] Retrieving book info...
> > [#] API: Out-of-Session (Authentication credentials were not provided.).
> > [!] Aborting...

{
  "orm-rt": "",
  "groot_sessionid": "",
  "logged_in": "y",
  "orm-jwt": "",
  "BrowserCookie": "",
  "csrfsafari": "",
  "salesforce_id": "",
  "sessionid": "",
  "csrftoken": ""
}

I was able to get it to work when I used the above cookies.json file

**Comment by vinayakg** [comment]
> This is what worked in Firefox.
> 
> 1. As @dkuzma2 mentioned, In the browser console run:
>    `var output = {};document.cookie.split(/\s*;\s*/).forEach(function(pair) {pair = pair.split(/\s*=\s*/);output[pair[0]] = pair.splice(1).join('=');});console.log(JSON.stringify(output));`
> 2. Edit safaribooks.py and add a new line
>    `PROFILE_URL = "https://www.oreilly.com/member/"`
>    right below the line
>    `PROFILE_URL = SAFARI_BASE_URL + "/profile/"`
> 3. Run
>    `python3 safaribooks.py <BOOKID>`

Works in Microsoft Edge as well Version 80.0.361.69 (Official build) (64-bit).

**Comment by rda3mon** [comment]
This no longer works. Just use one of the api calls from browser network activity to take cookie and convert into json and place it in cookies.json file. That should work.

**Comment by brunoscota** [comment]
> This no longer works. Just use one of the api calls from browser network activity to take cookie and convert into json and place it in cookies.json file. That should work.

for me also is not working anymore. Now I need to copy the cookie mannually via browser
