### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by jbuning** [lorenzodifuccia/safaribooks#20]
Tried to download and here's the error:

[-] Logging into Safari Books Online...
[*] Retrieving book info...
[#] API: book's not present in Safari Books Online.
    The book identifier is the digits that you can find in the URL:
    `https://www.safaribooksonline.com/library/view/book-name/XXXXXXXXXXXXX/`
[+] Please delete all the `<BOOK NAME>/OEBPS/*.xhtml` files and restart the program.
[!] Aborting...

**Comment by lorenzodifuccia** [comment]
I really appreciate your _exhaustive_ issue name.
I'll close the issue in few day if you don't help me better.

**Comment by cregnier** [comment]
Here is a similar one for me.  I was able to test one text and now receive this:
[#] Unhandled Exception: Expecting value: line 1 column 320 (char 319) (type: JSONDecodeError)
                                                                                             [+] Please delete all the `<BOOK NAME>/OEBPS/*.xhtml` files and restart the program.
                                                                                             [!] Aborting...

I have tried to find all OEBPS and xhtml files and even after this and re-cloning the repo - no luck.  I am not sure if it is a python lib at the line of code that is holding something open or.  Even a reboot does not matter.  Any suggestions.

**Comment by lorenzodifuccia** [comment]
Could you send me the ID of the book that you tried to download?

**Comment by guillaumevincent** [comment]
Hello @lorenzodifuccia, I got this issue for book id: 9780134434964
It works with the ` --no-kindle` option

**Comment by vivsrivastav** [comment]
Guess the problem still exists. I tried `--no-cookies` , `--no-kindle` 
```
python3 safaribooks.py --cred "username@password" --no-cookies --no-kindle 9781491963036
                                                                                                                                                                          
       ____     ___         _
      / __/__ _/ _/__ _____(_)
     _\ \/ _ `/ _/ _ `/ __/ /
    /___/\_,_/_/ \_,_/_/ /_/
      / _ )___  ___  / /__ ___
     / _  / _ \/ _ \/  '_/(_-<
    /____/\___/\___/_/\_\/___/

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[-] Logging into Safari Books Online...                                                                                                                                   
[#] Login: no CSRF Token found in the page. Unable to continue the login. Try again...                                                                                    
[+] Please delete all the `<BOOK NAME>/OEBPS/*.xhtml` files and restart the program.                                                                                      
[!] Aborting...         
```

There is also a log file generated which is basically javascript.

**Comment by giny8i8** [comment]
Me and my friend, both have this same CSRF error for some time now. As he is a programmer (I am not) he suspects (without looking into anything), that Safari might have changed the page, resulting in a response where this token can not be found. Maybe Safari switched to asynchronous JavaScript or something similar, he says.

**Comment by CodeTripper** [comment]
I have the same issue:
Logging into Safari Books Online...                                                          
[#] Login: no CSRF Token found in the page. Unable to continue the login. Try again...           
[+] Please delete all the `<BOOK NAME>/OEBPS/*.xhtml` files and restart the program.             
[!] Aborting...

**Comment by lorenzodifuccia** [comment]
Linked to #94
