### ISSUE TITLE
Broken download links for images

### ISSUE THREAD

**Issue by alx0x41** [lorenzodifuccia/safaribooks#201]
Hi,
Was using this script on windows - both with native Python installation and with the Cygwin package. In both cases images did not download properly - no error messages, but the files where all empty and 1kb in size.
Found the reason in `def link_replace(self, link): ... link = urljoin(self.base_url, link)`. Here the `link` values actually begin with '../', so when joining it eats up the last part of the base_url.
Sorry, for not suggesting a proper patch - I didn't investigate for the root cause and just made a local dirty patch with string.replace.

**Comment by noxymon** [comment]
yes, this issue fixed at #200,
or, if you don't mind you can try a fork version of mine. .. test if the problem solved.

**Comment by alx0x41** [comment]
Your version works fine with images located just in the images directory at the server. But there are books (for example 9781118238936) that have the OEBPS directory in their image path. Your version doesn't download those.
On the other had your script downloads CSSs. I didn't realise that those were skipped in the original version :)

**Comment by noxymon** [comment]
hmm...interesting, 
try it by now, I purpose new method to collecting image links

**Comment by alx0x41** [comment]
yes, now everything seems ok

**Comment by TheSnoozer** [comment]
Please get the latest version, this issue should be fixed by https://github.com/lorenzodifuccia/safaribooks/commit/d339d9dd0ff4b80855b806b7265105bd5ec79112

**Comment by alx0x41** [comment]
> Please get the latest version, this remaining css or image downloading issue should be fixed by [d339d9d](https://github.com/lorenzodifuccia/safaribooks/commit/d339d9dd0ff4b80855b806b7265105bd5ec79112)

Nope, the above mentioned problem with images located in OEBPS directory exists in this commit.

**Comment by raftgs** [comment]
One workaround (or solution?) could be add
```
                    if urlparse(link).path.split('/')[0] == '..':
                        link = urlparse(link).path.split('/', 1)[1]
```
into link_replace function, just above
`                    link = urljoin(self.base_url, link)
`

**Comment by raftgs** [comment]
One workaround (or solution?) could be add
```
                    if urlparse(link).path.split('/')[0] == '..':
                        link = urlparse(link).path.split('/', 1)[1]
```
into link_replace function, just above
`                    link = urljoin(self.base_url, link)
`

**Comment by TheSnoozer** [comment]
Mhh this might be related to the observation in https://github.com/lorenzodifuccia/safaribooks/issues/212#issuecomment-623030088

Could you please provide the book-ids where this issue can be observed? As of now i would guess it would be a similar issue.
