### ISSUE TITLE
unable to download images 

### ISSUE THREAD

**Issue by samascience** [lorenzodifuccia/safaribooks#206]
Caused by SSLError(SSLError("read error: Error([('SSL routines', 'ssl3_read_bytes', 'sslv3 alert bad record mac

 Downloading book contents... (35 chapters)
    [#############################################################################################################] 100%
[-] Downloading book CSSs... (0 files)
[-] Downloading book images... (1963 files)
[#] HTTPSConnectionPool(host='learning.oreilly.com', port=443): Max retries exceeded with url: /library/view/rhcsarhce-red-hat/9780071841948/0071841946.jpg (Caused by SSLError(SSLError("read error: Error([('SSL routines', 'ssl3_read_bytes', 'sslv3 alert bad record mac')],)",),))
[#] Error trying to retrieve this image: 0071841946.jpg
    From: https://learning.oreilly.com/library/view/rhcsarhce-red-hat/9780071841948/0071841946.jpg
[#] ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
[#] ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
[#] ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
[#] ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
[#] Error trying to retrieve this image: job.jpg

**Comment by TheSnoozer** [comment]
Please get the latest version, this issue should be fixed by https://github.com/lorenzodifuccia/safaribooks/commit/d339d9dd0ff4b80855b806b7265105bd5ec79112
