### ISSUE TITLE
Images are not being downloaded properly

### ISSUE THREAD

**Issue by fuckyourselfup** [lorenzodifuccia/safaribooks#214]
JPEG Images in books with images are not being downloaded properly, and instead is downloaded a PNG like file with Adobe XMP metadata and an almost empty image of 1x1 px, all weighting 953 bytes.

This does not seem to occur in all books, but just in some of them, I could not know which ones, how or why.

![ss](https://user-images.githubusercontent.com/25434695/81023440-c740f780-8e46-11ea-93bf-a94adde8c2e9.PNG)

**Comment by TheSnoozer** [comment]
related to https://github.com/lorenzodifuccia/safaribooks/issues/212#issuecomment-623030088

**Comment by nrenzoni** [comment]
This merge-request fixes the problem: https://github.com/lorenzodifuccia/safaribooks/pull/218.

**Comment by TheSnoozer** [comment]
https://github.com/lorenzodifuccia/safaribooks/pull/218 was merged, could you get the latest version and retry if this issue is still present?

**Comment by midejesus** [comment]
I had the same problem and the fix worked for me.
