### ISSUE TITLE
epub generated is partial

### ISSUE THREAD

**Issue by vinayakg** [lorenzodifuccia/safaribooks#215]
I have tried the methods suggest in [Issue 150] (https://github.com/lorenzodifuccia/safaribooks/issues/150) and I am still getting complete book.
I tried firefox and chrome, have also looked at the cookies one by one, but I still cant seem to get this to work.
I have not seen the code yet, but if book is partially downloaded it cannot be a auth issue. Dont see any error when running the command
![image](https://user-images.githubusercontent.com/1701204/81162825-6da60d80-8fab-11ea-8050-d509a2904226.png)

Please help if any of you have already solved.
Repro steps

- Try downloading 9781491965962 and go to the end of the chapter, it will be partial.
- You will observe this in all the chapters (attaching few images)
![image](https://user-images.githubusercontent.com/1701204/81162582-0c7e3a00-8fab-11ea-9851-c85f7551b0be.png)
![image](https://user-images.githubusercontent.com/1701204/81162627-1f910a00-8fab-11ea-8724-7fd6c654207b.png)

**Comment by lorenzodifuccia** [comment]
Are you reading the EPUB with Apple iBook?
Could you try to convert the EPUB to EPUB with Calibre?
If you download Calibre, you will find also the command line `ebook-converter` tool, just run:
`ebook-converter <original_epub>.epub <clear_epub>.epub`
This will clean up the EPUB content and it will not fail to display as incomplete on ebook reader as iBook.

**Comment by vinayakg** [comment]
@lorenzodifuccia this solved the problem
Got a bunch of CSS errors though, not sure if I need to worry about them
```
Ignoring CSS rule with invalid selector: u'input:read-only' (The pseudo-class :read-only is not supported)
Ignoring CSS rule with invalid selector: u'button::-moz-focus-inner' (The pseudo-class :-moz-focus-inner is not supported)
Ignoring CSS rule with invalid selector: u'.searchbox .search-query:focus::-webkit-input-placeholder' (The pseudo-class :-webkit-input-placeholder is not supported)
Ignoring CSS rule with invalid selector: u'.wrap-search-form .search-query:focus::-webkit-input-placeholder' (The pseudo-class :-webkit-input-placeholder is not supported)
Ignoring CSS rule with invalid selector: u'.searchbox select.search-params::-ms-expand' (The pseudo-class :-ms-expand is not supported)
Ignoring CSS rule with invalid selector: u'.wrap-search-form select.search-params::-ms-expand' (The pseudo-class :-ms-expand is not supported)
Ignoring CSS rule with invalid selector: u'.sbo-inpage-toc .tabs li::selection' (The pseudo-class :selection is not supported)
Ignoring CSS rule with invalid selector: u'#id_username:-moz-placeholder' (The pseudo-class :-moz-placeholder is not supported)
Ignoring CSS rule with invalid selector: u'#id_username:-ms-input-placeholder' (The pseudo-class :-ms-input-placeholder is not supported)
Ignoring CSS rule with invalid selector: u'#id_username::-webkit-input-placeholder' (The pseudo-class :-webkit-input-placeholder is not supported)
Ignoring CSS rule with invalid selector: u'#id_username::-moz-placeholder' (The pseudo-class :-moz-placeholder is not supported)
Ignoring CSS rule with invalid selector: u'input#id_username:-ms-input-placeholder' (The pseudo-class :-ms-input-placeholder is not supported)
Ignoring CSS rule with invalid selector: u'input#id_username::-moz-placeholder' (The pseudo-class :-moz-placeholder is not supported)
Ignoring CSS rule with invalid selector: u'input#id_username::-webkit-input-placeholder' (The pseudo-class :-webkit-input-placeholder is not supported)
Ignoring CSS rule with invalid selector: u'body.night-mode #sbo-rt-content .annotator-wrapper ::selection' (The pseudo-class :selection is not supported)
Ignoring CSS rule with invalid selector: u'body.night-mode #sbo-rt-content .annotator-wrapper ::-moz-selection' (The pseudo-class :-moz-selection is not supported)
```

Also images have been rescaled and my file size has become 50%. Do I need to worry about this and should I change any settings to maintain the same quality? Assuming lower images will show pixelated on larger screens.
Also, Could you please explain how this solved the problem?

**Comment by vinayakg** [comment]
Also the original epub before conversion looks fine on epub-viewer from calibre

**Comment by sesteva** [comment]
I've pulled the latest code today and I'm also getting partial downloads. Each chapter only contains the very first page. 
Am I missing anything?

**Comment by lorenzodifuccia** [comment]
> I've pulled the latest code today and I'm also getting partial downloads. Each chapter only contains the very first page.
> Am I missing anything?

Try: https://github.com/lorenzodifuccia/safaribooks/issues/215#issuecomment-631687918

**Comment by sesteva** [comment]
I've tried converting in calibre from epub to epub. Same thing, every chapter only contains the first few paragraphs.
