### ISSUE TITLE
Unhandled Exception: 'Response' object has no attribute 'next' (type: AttributeError)

### ISSUE THREAD

**Issue by samascience** [lorenzodifuccia/safaribooks#219]
____     ___         _
      / __/__ _/ _/__ _____(_)
     _\ \/ _ `/ _/ _ `/ __/ /
    /___/\_,_/_/ \_,_/_/ /_/
      / _ )___  ___  / /__ ___
     / _  / _ \/ _ \/  '_/(_-<
    /____/\___/\___/_/\_\/___/

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[-] Logging into Safari Books Online...
[#] Unhandled Exception: 'Response' object has no attribute 'next' (type: AttributeError)
[!] Aborting...

**Comment by chel034** [comment]
[19/May/2021 13:31:43] ** Welcome to SafariBooks! **
[19/May/2021 13:31:43] Logging into Safari Books Online...
[19/May/2021 13:31:44]   File "safaribooks.py", line 1112, in <module>
    SafariBooks(args_parsed)
  File "safaribooks.py", line 335, in __init__
    self.do_login(*args.cred)
  File "safaribooks.py", line 471, in do_login
    next_parameter = parse_qs(urlparse(response.request.url).query)["next"][0]

[19/May/2021 13:31:44] Unhandled Exception: 'next' (type: KeyError)
[19/May/2021 13:31:44] Last request done:
	URL: https://www.google.com/?q=Why+am+I+on+this+blacklist
	DATA: None
	OTHERS: {}

	200
	Date: Wed, 19 May 2021 17:31:43 GMT
	Expires: -1
	Cache-Control: private, max-age=0
	Content-Type: text/html; charset=UTF-8
	Strict-Transport-Security: max-age=31536000
	BFCache-Opt-In: unload
	P3P: CP="This is not a P3P policy! See g.co/p3phelp for more info."
	Content-Encoding: gzip
	Server: gws
	X-XSS-Protection: 0
	X-Frame-Options: SAMEORIGIN
	Set-Cookie: 1P_JAR=2021-05-19-17; expires=Fri, 18-Jun-2021 17:31:43 GMT; path=/; domain=.google.com; Secure; SameSite=none, NID=216=hfj0_cLYszjCrcXPC6Ppl3CIhVrLz_tCdzfdQ7rXt4l1DILMYwf-LqdWHx2x7x9935y5F13N2q58D8wY3kEnjwmA7_Pl3-2WbKCCwLm7kpTsxxxbYsEH_W25Z4N9LUkxH1ZJ4NJ9rbmcyNTHIMy7mKb-Qg4puGjY15OvGDCw2sw; expires=Thu, 18-Nov-2021 17:31:43 GMT; path=/; domain=.google.com; Secure; HttpOnly; SameSite=none
	Alt-Svc: h3-29=":443"; ma=2592000,h3-T051=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
	Transfer-Encoding: chunked
