### ISSUE TITLE
sso_cookies.py not working when "=" equals symbol is present

### ISSUE THREAD

**Issue by danielctrl** [lorenzodifuccia/safaribooks#220]
After trying to use the **sso_cookies.py** to crate the cookies.json file, it couldn't authenticate due to an issue in the JSON creation.

When the following pattern is present (I have omitted the rest of the cookies and formated the JSON for obvious reason):
`{
	"_dd_s":"rum=1&expire=111",
	"_fbp":"fb.1.111.111"
}`

It is converting to:
`{
	"_dd_s:rum": "1&expire=111,_fbp:fb.1.111.111"
}`

Some additional info:
- The original JSON was extracted from Firefox's network tab, as indicated in the [Elrob's commentary](https://github.com/lorenzodifuccia/safaribooks/issues/150#issuecomment-555423085)
- I called the command in PowerShell, using the following sintax: `python3 sso_cookies.py '"_dd_s":"rum=1&expire=111.......'`

**Comment by gusleyva** [comment]
Hi!
I did today and it worked, just to double-check, 
From your web browser:
- Open devs tools
- Navigate to Network tab
- Find the cookie, this can be found from the header tab, scroll down until you find where it says "cookie" or to the cookies tab, copy all of the
I.e. "cookie: BrowserCookie=123123123123-123123-123123-123123; _vwo_uuid_v2=12312313123; ......."

From your command line, navigate where you have the safaribooks project 
- cd safaribboks
Use the following command and the parameter should be the cookie adding " to the beginning and to the end.
- python3 sso_cookies.py "cookie: BrowserCookie=123123123123-123123-123123-123123; _vwo_uuid_v2=12312313123; ......."
If everything is ok you will see:
$ Done! Cookie Jar saved into `cookies.json`. Now you can run `safaribooks.py` without the `--cred` argument...

Now execute the initial command from the basic instructions
I.e. python3 safaribooks.py [bookId]
$ python3 safaribooks.py 123123123123

That worked for me.

**Comment by 5ruberuto** [comment]
> Hi!
> I did today and it worked, just to double-check,
> From your web browser:
> 
> * Open devs tools
> * Navigate to Network tab
> * Find the cookie, this can be found from the header tab, scroll down until you find where it says "cookie" or to the cookies tab, copy all of the
>   I.e. "cookie: BrowserCookie=123123123123-123123-123123-123123; _vwo_uuid_v2=12312313123; ......."
> 
> From your command line, navigate where you have the safaribooks project
> 
> * cd safaribboks
>   Use the following command and the parameter should be the cookie adding " to the beginning and to the end.
> * python3 sso_cookies.py "cookie: BrowserCookie=123123123123-123123-123123-123123; _vwo_uuid_v2=12312313123; ......."
>   If everything is ok you will see:
>   $ Done! Cookie Jar saved into `cookies.json`. Now you can run `safaribooks.py` without the `--cred` argument...
> 
> Now execute the initial command from the basic instructions
> I.e. python3 safaribooks.py [bookId]
> $ python3 safaribooks.py 123123123123
> 
> That worked for me.

I followed your instructions and I can confirm it worked. I was using Firefox. I copy all the values of cookie tab, change the format insted of "key":'value" to key=value and pasted all the string in oss_cookies.py to generate the cookies.json file.

Thanks a lot.

**Comment by MuhammedElGanzory** [comment]
How to solve that error !! 
Traceback (most recent call last):
  File "sso_cookies.py", line 13, in <module>
    import safaribooks
  File "C:\Users\*****\Desktop\safaribooks\safaribooks.py", line 12, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by gusleyva** [comment]
> How to solve that error !!
> Traceback (most recent call last):
> File "sso_cookies.py", line 13, in
> import safaribooks
> File "C:\Users*****\Desktop\safaribooks\safaribooks.py", line 12, in
> import requests
> ModuleNotFoundError: No module named 'requests'

That is a python dependency/library, "download" requests:
$ sudo pip install requests (or pip3 install requests for python3) if you have pip installed. 

If pip is installed but not in your path you can use 
python -m pip install requests (or python3 -m pip install requests for python3)

**Comment by lorenzodifuccia** [comment]
Please read the [README.md](https://github.com/lorenzodifuccia/safaribooks#requirements--setup).
This is a **Python3** program!

**Comment by MuhammedElGanzory** [comment]
My Exported cookies should be like that :
{
  "BrowserCookie": "XXX",
  "csrfsafari": "XXX",
  "logged_in": "y",
  "orm-jwt": "XXX",
  "orm-rt": "XXX",
  "sessionid": "XXX",
  "reader_preferences": "XXX",
}

**Comment by MuhammedElGanzory** [comment]
Another error here: 
[#] Unhandled Exception: Expecting property name enclosed in double quotes: line 9 column 1 (char 1155) (type: JSONDecodeError)
                                                                                                               [!] Aborting... 
  How to solve !!
