### ISSUE TITLE
aborting

### ISSUE THREAD

**Issue by obar1** [lorenzodifuccia/safaribooks#224]
for this book
https://learning.oreilly.com/library/view/frank-kanes-taming/9781787287945/

if works only if I add `-kindle` option 

othw get error `namespace something not found`
I copied the leftover from Books

[Frank Kane_s Taming Big Data with Apache Spark and Python (9781787287945).zip](https://github.com/lorenzodifuccia/safaribooks/files/5154692/Frank.Kane_s.Taming.Big.Data.with.Apache.Spark.and.Python.9781787287945.zip)

**Comment by lorenzodifuccia** [comment]
Could you paste the error please?

**Comment by obar1** [comment]
I tried again after wiping the `Books` folder and it worked
closing this

![image](https://user-images.githubusercontent.com/387386/93000297-c2443100-f527-11ea-9ba0-1b41610e6b73.png)

**Comment by obar1** [comment]
Unhandled Exception: 'Namespace' object has no attribute 'no_kindle' (type: AttributeError)

**Comment by obar1** [comment]
but deleting the Books and retrying it works .. so it's kind of wired

**Comment by lorenzodifuccia** [comment]
Thanks, fixed!
