### ISSUE TITLE
book download using company mail id

### ISSUE THREAD

**Issue by verma-rohit80** [lorenzodifuccia/safaribooks#228]
Hi,
I have to use my ACM credentials  to log into O Reilly. It is not a straight forward login and password setup but rather  couple of steps involved:
1. Provide acm mail id  in login
2. It is directed to ACM and there i provide my mail id and password
3. Access is granted.

I there a way to get around downloading book using 2 step verification process ?

**Comment by lorenzodifuccia** [comment]
Read: https://github.com/lorenzodifuccia/safaribooks/issues/150#issuecomment-555423085
