### ISSUE TITLE
ModuleNotFoundError when running

### ISSUE THREAD

**Issue by glennawb** [lorenzodifuccia/safaribooks#229]
I get this... 

After running `python3 safaribooks.py --cred "xxx" 9781782175339`:

`Traceback (most recent call last):
  File "safaribooks.py", line 16, in <module>
    from lxml import html, etree
ModuleNotFoundError: No module named 'lxml'`

**Comment by lorenzodifuccia** [comment]
RTFM: https://github.com/lorenzodifuccia/safaribooks#requirements--setup

**Comment by glennawb** [comment]
I should have added, I followed those steps as well.

**Comment by lorenzodifuccia** [comment]
And you are unable to run the program... Could you paste the output of the following commands?
- `pip --version`
- `pip freeze`
