### ISSUE TITLE
no csrf token found, can't login

### ISSUE THREAD

**Issue by Imallek** [lorenzodifuccia/safaribooks#23]
It says:
No CSRF token found on the page, Please try login again
Have tried many times, on many different pages, same response. 
---------------------------------------------------------------------------------------------------

[21/Jul/2018 22:10:29] ** Welcome to SafariBooks! **
[21/Jul/2018 22:10:29] Logging into Safari Books Online...
[21/Jul/2018 22:11:01] Login: no CSRF Token found in the page. Unable to continue the login. Try again...
[info_9780134278308.log](https://github.com/lorenzodifuccia/safaribooks/files/2216373/info_9780134278308.log)

**Comment by Imallek** [comment]
script is working fine, there's problem with the website.
IP blocked or maybe website down.

**Comment by billhongs** [comment]
Login: no CSRF Token found in the page. Unable to continue the login. Try again...
