### ISSUE TITLE
Question--Unable to perform auth login

### ISSUE THREAD

**Issue by hyclin** [lorenzodifuccia/safaribooks#230]
```
                                                                                
 ██████╗     ██████╗ ██╗  ██╗   ██╗██████╗ 
██╔═══██╗    ██╔══██╗██║  ╚██╗ ██╔╝╚════██╗
██║   ██║    ██████╔╝██║   ╚████╔╝   ▄███╔╝
██║   ██║    ██╔══██╗██║    ╚██╔╝    ▀▀══╝ 
╚██████╔╝    ██║  ██║███████╗██║     ██╗   
 ╚═════╝     ╚═╝  ╚═╝╚══════╝╚═╝     ╚═╝                                           

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[-] Logging into Safari Books Online...                                         
[#] Login: unable to perform auth login to Safari Books Online.                 
[*] Details:
    Unexpected error!
[!] Aborting...       
```

My password does have special characters but I made sure to escaped them. Also tried changing password to one that doesn't contain special characters. Still unable to log in and keep getting the same error. Any advise?

**Comment by obar1** [comment]
hi @hyclin - just for fun try with this fork it you get throug (at least)
https://github.com/elrob/safaribooks

**Comment by pedro-correia-tech** [comment]
Same error here. Even on your fork @obar1

**Comment by lorenzodifuccia** [comment]
Have you try with the latest version?

**Comment by PawelFaron** [comment]
Same problem. Login and password without any special characters. Version cloned today.

**Comment by obar1** [comment]
you need to  use  " " mate
ex
"mypwdwith#inside"
NOT
mypwdwith#inside

**Comment by rodrigoascencio** [comment]
i also have this issue, won't tell me what the problem is but wont auth
