### ISSUE TITLE
Download broken - not an auth issue

### ISSUE THREAD

**Issue by piovac** [lorenzodifuccia/safaribooks#234]
Download broken - not an auth issue..

`python3 ./safaribooks.py --login --preserve-log 9781119383000`

Gives the following error:

```
[-] Logging into Safari Books Online...
[-] Successfully authenticated.
[*] Retrieving book info...
[#] Unhandled Exception: 'rights' (type: KeyError)
[!] Aborting...
```

**Comment by Bomberdash** [comment]
Good afternoon!
I got the same error. Pip updated.
I can read the book itself online on the website, but the download no longer works. This error is issued for any book.

**Comment by piovac** [comment]
Started today ~ worked till few hours ago

**Comment by piovac** [comment]
Started working again. It was maybe a server problem.

**Comment by ungarida** [comment]
Experiencing the same today. It seems to be a server side problem... maybe a very slow connectivity on their side.
