### ISSUE TITLE
Issue with downloading older Books

### ISSUE THREAD

**Issue by falaqm** [lorenzodifuccia/safaribooks#236]
I observed an error when downloading older Oreilly books. 
https://learning.oreilly.com/library/view/design-patterns-elements/0201633612/
 
Unhandled Exception: 'rights' (type: KeyError)

**Comment by axrt** [comment]
Same here, the book is https://learning.oreilly.com/library/view/refactoring-at-scale/9781492075523/

`[-] Logging into Safari Books Online...
[-] Successfully authenticated.
[*] Retrieving book info...
[#] Unhandled Exception: 'rights' (type: KeyError)
[!] Aborting...
`
will be eager to help out debug with guidance, cuz not very familiar with the code yet.

**Comment by aldovilardy** [comment]
It's happening with all books not just with the old ones:

 ██████╗     ██████╗ ██╗  ██╗   ██╗██████╗
██╔═══██╗    ██╔══██╗██║  ╚██╗ ██╔╝╚════██╗
██║   ██║    ██████╔╝██║   ╚████╔╝   ▄███╔╝
██║   ██║    ██╔══██╗██║    ╚██╔╝    ▀▀══╝
╚██████╔╝    ██║  ██║███████╗██║     ██╗
 ╚═════╝     ╚═╝  ╚═╝╚══════╝╚═╝     ╚═╝

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[-] Logging into Safari Books Online...
[-] Successfully authenticated.
[*] Retrieving book info...
[#] Unhandled Exception: 'rights' (type: KeyError)
[!] Aborting...

**Comment by jacabreragt** [comment]
Comment the line 177 on safaribooks.py

Aparently O'Reilly changed the API and removed the 'rights' field.

**Comment by jacabreragt** [comment]
O'Reilly changed the API.

Here is the fix: [https://github.com/jacabreragt/safaribooks/commit/250d1c611b970d53ce93ee6fe630cd582928370c](url)

**Comment by falaqm** [comment]
This one worked for me.

https://github.com/nhonaitran/safaribooks/commit/fef3b21dd42617f62f9a416c9dce6c981e011bb9

**Comment by falaqm** [comment]
> O'Reilly changed the API.
> 
> Here is the fix: [https://github.com/jacabreragt/safaribooks/commit/250d1c611b970d53ce93ee6fe630cd582928370c](url)

not able to open the link

**Comment by jacabreragt** [comment]
> > O'Reilly changed the API.
> > Here is the fix: [https://github.com/jacabreragt/safaribooks/commit/250d1c611b970d53ce93ee6fe630cd582928370c](url)
> 
> not able to open the link

I'm sorry.  Edited.

**Comment by Bomberdash** [comment]
bad url

**Comment by jacabreragt** [comment]
> bad url

[https://github.com/jacabreragt/safaribooks/commit/250d1c611b970d53ce93ee6fe630cd582928370c](https://github.com/jacabreragt/safaribooks/commit/250d1c611b970d53ce93ee6fe630cd582928370c)

**Comment by Bomberdash** [comment]
Good afternoon!
Thank you for your constant help !!!
Making these changes to the safaribooks.py file not only does not solve this problem, but also leads to another
Here's what is given out on an attempt to download
https://learning.oreilly.com/library/view/advanced-engineering-mathematics/9781284105971/
"~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

[-] Logging into Safari Books Online ...

[-] Successfully authenticated.

[*] Retrieving book info ...

[#] Unhandled Exception: 'description' (type: KeyError)

[!] Aborting ... "

**Comment by lorenzodifuccia** [comment]
Try pull-ing new code (thanks to @nhonaitran with PR #239)
