### ISSUE TITLE
Safarybooks.py not working anymore. Unhandled Exception: 'rights'

### ISSUE THREAD

**Issue by tanvirrony** [lorenzodifuccia/safaribooks#237]
Getting following error.
[-] Logging into Safari Books Online...
[-] Successfully authenticated.
[*] Retrieving book info...
[#] Unhandled Exception: 'rights' (type: KeyError)
[!] Aborting...

**Comment by jacabreragt** [comment]
Sometimes I receive the same error but retry and it works.

**Comment by jacabreragt** [comment]
Comment the line 177 on safaribooks.py

Aparently O'Reilly changed the API and removed the 'rights' field.

**Comment by jacabreragt** [comment]
O'Reilly changed the API.

Here is the fix: [https://github.com/jacabreragt/safaribooks/commit/250d1c611b970d53ce93ee6fe630cd582928370c](url)

**Comment by ashish2199** [comment]
@jacabreragt Can you please get this merged in this repo as well if it's working.

**Comment by fyxtro** [comment]
@ashish2199  if you make the same changes you see in the commit it works perfectly for now.

**Comment by tanvirrony** [comment]
Thanks @nhonaitran & @jacabreragt.
After changing 177 & 964 line now its working fine.

**Comment by tanvirrony** [comment]
Thanks @nhonaitran & @jacabreragt.
After changing 177 & 964 line now its working fine.

**Comment by TheDiegoFrade** [comment]
Thanks! @nhonaitran @jacabreragt

**Comment by lorenzodifuccia** [comment]
Try to pull new commit (thanks to @nhonaitran with PR #239 and @avineshwar with PR #245)

Thank you @jacabreragt
