### ISSUE TITLE
Out of session error

### ISSUE THREAD

**Issue by pvzweden** [lorenzodifuccia/safaribooks#24]
Hi,

The script does not seem to work anymore, probably some API things have changed?

The error I get from the script: 

> [-] Logging into Safari Books Online...                                                                                                                    
> [*] Retrieving book info...                                                                                                                                
> [#] API: Out-of-Session (Authentication credentials were not provided.). 
> 

Last Log entry (Some info made anonyous):

> '
> [02/Aug/2018 14:15:08] Last request done:
>         URL: https://www.safaribooksonline.com/api/v1/book/9780071744324/
>         DATA: None
>         OTHERS: {}
> 
>         401
>         Server: nginx/1.10.3 (Ubuntu)
>         Content-Type: application/json
>         x-xss-protection: 1; mode=block
>         Content-Language: en-US
>         strict-transport-security: max-age=3600; includeSubDomains
>         Allow: GET, HEAD, OPTIONS
>         WWW-Authenticate: Bearer realm="api"
>         ETag: "d5972c9c85159c7a7494e2554c26def1"
>         x-content-type-options: nosniff
>         X-Frame-Options: SAMEORIGIN
>         Set-Cookie: api_key=; expires=Thu, 01-Jan-1970 00:00:00 GMT; Max-Age=0; Path=/, logged_in=; expires=Thu, 01-Jan-1970 00:00:00 GMT; Max-Age=0; Path=/, sessionid=xxxx Domain=.www.safaribooksonline.com; expires=Thu, 16-Aug-2018 12:15:10 GMT; Max-Age=1209600; Path=/; secure
>         Accept-Ranges: bytes, bytes
>         Content-Length: 58
>         Date: Thu, 02 Aug 2018 12:15:08 GMT
>         Via: 1.1 varnish
>         Connection: keep-alive
>         X-Client-IP: XXXX
>         X-Served-By: cache-ams4138-AMS
>         X-Cache: MISS
>         X-Cache-Hits: 0
>         X-Timer: S1533212108.238304,VS0,VE169
>         Vary: Accept, Accept-Language, Authorization, Cookie
> 
> {"detail":"Authentication credentials were not provided."}
> '

Started the script with --cred "credentials" (so credentials were provided)

**Comment by lorenzodifuccia** [comment]
> The script does not seem to work anymore

Please: https://ibb.co/dNOCAe

---

Lets try to solve _this_ problem.
Could you add those two lines **after** line `477` in `safaribooks.py`?

```python
print(response)
print(self.HEADERS["cookie"])
```

The result should be:
```python
    def get_book_info(self):
        response = self.requests_provider(self.api_url)
        if response == 0:
            self.display.exit("API: unable to retrieve book info.")

        print(response)
        print(self.HEADERS["cookie"])
        response = response.json()
        if not isinstance(response, dict) or len(response.keys()) == 1:
            self.display.exit(self.display.api_error(response))
```

Let me know...

**Comment by miguelraulb** [comment]
Hi Lorenzo,

I came across with the same issue and it's my first time using the script, however I use SSO. I checked [here](https://github.com/lorenzodifuccia/safaribooks/issues/2) for the SSO support and I started creating my `cookies.json` and I created a file with the values I got from the lines you add but I'm still getting the error, below is what I get:

>[-] Logging into Safari Books Online...                                                                                                                                                       
>[*] Retrieving book info...                                                                                                                                                                   
><Response [401]>
>BrowserCookie=550bb028-4150-452a-86a5-565bbb13826d; >corp_sessionid=ztsbviqiad09l7uancs23fxuohht8lwc; >csrfsafari=wAzW7hlMzdLRwG78xSeAWV3287h8SVKW; >original_referer="https://www.safaribooksonline.com/home/"; >sessionid=ekdbz9w0hafwuab4wrcobeiqhoftmr8p;
>[#] API: Out-of-Session (Authentication credentials were not provided.).                                                                                                                      
>
>[+] Please delete all the `<BOOK NAME>/OEBPS/*.xhtml` files and restart the program.                                                                                                          
>[!] Aborting...      

I hope this helps?

**Comment by lorenzodifuccia** [comment]
Yes, thanks for the comment.
Could you please check if the cookies are the same that you use in a valid browser session? I mean, are they still valid?
After that, could you post the content of `cookies.json` here?
Please replace cookie values with some Xs, cookies are sensible data to expose on Internet due to hijacking attack.
Thanks.

**Comment by lorenzodifuccia** [comment]
I'm sorry I didn't know the existence of an "old/classic" account type.
Let me/us know about that.
Thanks.

**Comment by Shankersfdc** [comment]
@miguelraulb 
I Got The Same Issue, But I Didn't Get That, How To Cookies Values To Cookies Files?? 
Can Yu Please Help Me With This..

**Comment by dexter101010** [comment]
Change your ip and try again!

**Comment by Shankersfdc** [comment]
@dexter101010 
Hi Dexter, Am Sorry If Am Really Asking Silly Qn's 
But Can Yu Please Tell Me How To Change It?
Am A Bit New To Tech..

**Comment by dexter101010** [comment]
Use vpn or proxy.

**Comment by Shankersfdc** [comment]
Okay.. So Can I Connect With Other Mobile And Give A Try??

**Comment by Shankersfdc** [comment]
Hi @dexter101010 

Same Problem Again.. Tried With Different IP

**Comment by dexter101010** [comment]
Public ip have to be different. You can check what is your ip with google. Search "what is my ip"  then change your ip and check again. I'll check again from my side to see if i get same issue as you.

**Comment by Shankersfdc** [comment]
Guys.. Please Can Anyone Help Me With This.. Am Not Able To Download... Can Yu Give Me A Solution For Thiss...

**Comment by obar1** [comment]
use vitualenv @Shankersfdc
