### ISSUE TITLE
book_info unhandled exception

### ISSUE THREAD

**Issue by mancusoa74** [lorenzodifuccia/safaribooks#240]
hi there,
I have noticied that in some cases, the book_info dictionary is not complete.
As an example, this book 
https://learning.oreilly.com/library/view/ubuntu-linux-unleashed/9780136685395/

generates an exception unhandled as the rights key is not existing
[#] Unhandled Exception: 'rights' (type: KeyError)

I have already created a fix for it.

if you want I can create a pull request or paste the fix here

let me know in case this might help to improve this incredible tool

thnx
Antonio

**Comment by nhonaitran** [comment]
I think this is the same issue as issue #237.  I've put forth a [PR#239](https://github.com/lorenzodifuccia/safaribooks/pull/239) to fix this if you'd like try.

**Comment by mancusoa74** [comment]
> 
> 
> I think this is the same issue as #237. I've put forth [PR#239](https://github.com/lorenzodifuccia/safaribooks/pull/239) to fix this if you'd like to try.

Indeed you are right. I beg your pardon for my issue #240. I should have pay more attention to previous issues.

thnx

**Comment by nhonaitran** [comment]
No worries.  Just want to let you know there is a fix if you find it acceptable. Ai

**Comment by leakydata** [comment]
I had the same issue with the Rights exception, but I just download the fixed script and it works!! https://raw.githubusercontent.com/jacabreragt/safaribooks/250d1c611b970d53ce93ee6fe630cd582928370c/safaribooks.py

**Comment by lorenzodifuccia** [comment]
Try to pull new commit (thanks to @nhonaitran with PR #239 and @avineshwar with PR #245)

**Comment by mancusoa74** [comment]
Perfect! It solves the issue. thnx
