### ISSUE TITLE
Can't download books due to new error some kind of unhandled exception

### ISSUE THREAD

**Issue by rashapredator** [lorenzodifuccia/safaribooks#244]
I am getting a new kind of error when trying to download books. The error looks something like this:
`Unhandled Exception: 'rights' (type KeyError)`

**Comment by socarpl** [comment]
@rashapredator Go to "safaribooks.py" to line 177 and replace ("Rights", info["rights"]) with ("Rights", "whatever"). It's a workaround but it works. I dont have time to look into the info object, but seems it's lacking "rights" key. 

Trace:
[23/Nov/2020 20:18:52] ** Welcome to SafariBooks! **
[23/Nov/2020 20:18:52] Logging into Safari Books Online...
[23/Nov/2020 20:18:58] Successfully authenticated.
[23/Nov/2020 20:18:58] Retrieving book info...
[23/Nov/2020 20:18:59]   File "safaribooks.py", line 1112, in <module>
    SafariBooks(args_parsed)
  File "safaribooks.py", line 346, in __init__
    self.display.book_info(self.book_info)
  File "safaribooks.py", line 177, in book_info
    ("Rights", info["rights"]),

[23/Nov/2020 20:18:59] Unhandled Exception: 'rights' (type: KeyError)

**Comment by lorenzodifuccia** [comment]
Try to pull new commit (thanks to @nhonaitran with PR #239 and @avineshwar with PR #245)

Thank you @rashapredator

**Comment by Bomberdash** [comment]
This change does not work. Generates new mistakes
[-] Creating EPUB file ...

[#] API: [+] Use the `--cred` or` --login` options in order to perform the auth
login to Safari. Don't delete any files, just run again this program in order to
  complete the `.epub` creation!
For:
https://learning.oreilly.com/library/view/essential-ptc-mathcad//9780124104105
And it doesn't matter if you delete a directory or not. The error persists.

**Comment by avineshwar** [comment]
As mentioned in my PR, this was a likely situation, hence, this error. When I made a change for this locally, another error came up.

```
[-] Successfully authenticated.                                                                                                                
[*] Retrieving book info...                                                                                                                    
[-] Title: Advanced Engineering Mathematics, 6th Edition                                                                                       
[-] Authors: Zill                                                                                                                              
[-] Identifier: 9781284105971                                                                                                                  
[-] ISBN: 9781284105971                                                                                                                        
[-] Publishers: Jones & Bartlett Learning                                                                                                      
[-] Rights:                                                                                                                                    
[-] Description:                                                                                                                               
[-] Release Date: 2016-09-01                                                                                                                   
[-] URL: https://learning.oreilly.com/library/view/advanced-engineering-mathematics/9781284105971/                                             
[*] Retrieving book chapters...                                                                                                                
[#] Unhandled Exception: Expecting value: line 1 column 1 (char 0) (type: JSONDecodeError)                                                     
[!] Aborting...
```

**Comment by lorenzodifuccia** [comment]
Involuntarily closed...

I pushed a new change for the `description` error, let me know!

**Comment by C0rn3j** [comment]
Last commit breaks the app, particularly on line 951
```
            escape(aut.get("name", "n/d")])
```
You left an extra ] there

**Comment by lorenzodifuccia** [comment]
Yeah, typo. Pushed the fix.
