### ISSUE TITLE
Unhandled Exception: 'rights' (type: KeyError)

### ISSUE THREAD

**Issue by venkatasrinivasnamburi** [lorenzodifuccia/safaribooks#257]
I have used the approach to copy the /profile request call to cookies.json and tried to download a book, but i see the following error.

[-] Successfully authenticated.
[*] Retrieving book info...
[#] Unhandled Exception: 'rights' (type: KeyError)
[!] Aborting...

Any Help would be appreciated. I am running this on my mac machine.

**Comment by standurside** [comment]
looks like cannot get book_info from api
I hope someone resolve this prob

**Comment by standurside** [comment]
looks like cannot get book_info from api
I hope someone resolve this prob

**Comment by wangyung** [comment]
just removing this line, this problem can be resolved.
https://github.com/lorenzodifuccia/safaribooks/blob/master/safaribooks.py#L177

**Comment by venkatasrinivasnamburi** [comment]
Thank you @wangyung , It works!

**Comment by standurside** [comment]
I removed safaribooks.py #L177
but, Its showed another error follow

[-] Creating EPUB file...                                                                              
[#] Unhandled Exception: 'rights' (type: KeyError)                                                     
[+] Please delete the output directory

**Comment by venkatasrinivasnamburi** [comment]
Hi @standurside , the fix was not to remove the line, I have faced the same issue. I have updated my code using git pull and things started working for me. Please try and it should fix the issue.

**Comment by standurside** [comment]
@venkatasrinivasnamburi  Thnx so  much, It works.
```
root@kali:/safaribooks# git pull
Updating 950a3c7..c11c656
Fast-forward
 .gitignore     |  1 +
 Pipfile.lock   | 82 +++++++++++++++++++++++++++++++++++++++++++--------------------------------------
 safaribooks.py | 41 ++++++++++++++++++-----------------------
 3 files changed, 63 insertions(+), 61 deletions(-)
root@kali:/safaribooks# 
```
@wangyung have nice day
