### ISSUE TITLE
Crawler: error trying to retrieve this page: cover.html (Cover)

### ISSUE THREAD

**Issue by kolmant** [lorenzodifuccia/safaribooks#261]
Hi!

I'm trying to download a book and I get this error (tried with different ones, same result):

```
...
[-] Downloading book contents... (26 chapters)
[#] Crawler: error trying to retrieve this page: cover.html (Cover)
    From: https://learning.oreilly.com/api/v2/epubs/urn:orm:book:9781491903063/files/cover.html
[+] Please delete the output directory '/safaribooks/Books/Designing Data-Intensive Applications (9781491903063)' and restart the program.
[!] Aborting...
```
If I manually go to `https://learning.oreilly.com/api/v2/epubs/urn:orm:book:9781491903063/files/cover.html` I get the following error (HTTP 403), so I don't know if this is an issue related to my account or can be a general issue:

```
{
"detail": "You do not have permission to perform this action."
}
```

**Comment by ufolux** [comment]
Same problem.

**Comment by ufolux** [comment]
You need to add the book to your e-shelf  first

**Comment by zhiyi-zhang-duke** [comment]
Just a note. I had this issue too and realized that I just needed to sign back into my account. For some reason, if you were signed in at one point and the browser remembered that after say a restart, it'll bring up a pseudo session but you're not actually signed in. The script didn't like this but as soon as I signed in, it was perfectly fine.
