### ISSUE TITLE
ModuleNotFoundError: No module named 'lxml'

### ISSUE THREAD

**Issue by venkatasrinivasnamburi** [lorenzodifuccia/safaribooks#265]
see this issue on windows 10 machine when you run the **python3 safaribooks.py** command

Traceback (most recent call last):
  File "safaribooks.py", line 16, in <module>
    from lxml import html, etree
ModuleNotFoundError: No module named 'lxml'

**Comment by obar1** [comment]
did you run pip -r req ?

**Comment by venkatasrinivasnamburi** [comment]
pip <command> [options]

no such option: -r

**Comment by obar1** [comment]
https://stackoverflow.com/questions/38066631/what-does-r-do-in-pip-install-r-requirements-txt
