### ISSUE TITLE
https://www.google.com/?q=Why+am+I+on+this+blacklist?

### ISSUE THREAD

**Issue by chel034** [lorenzodifuccia/safaribooks#268]
[19/May/2021 15:39:08] Unhandled Exception: 'next' (type: KeyError)
[19/May/2021 15:39:08] Last request done:
	URL: https://www.google.com/?q=Why+am+I+on+this+blacklist
	DATA: None
	OTHERS: {}

	200
	Date: Wed, 19 May 2021 19:39:07 GMT
	Expires: -1
	Cache-Control: private, max-age=0
	Content-Type: text/html; charset=UTF-8
	Strict-Transport-Security: max-age=31536000
	BFCache-Opt-In: unload
	P3P: CP="This is not a P3P policy! See g.co/p3phelp for more info."
	Content-Encoding: gzip
	Server: gws
	X-XSS-Protection: 0
	X-Frame-Options: SAMEORIGIN
	Set-Cookie: 1P_JAR=2021-05-19-19; expires=Fri, 18-Jun-2021 19:39:07 GMT; path=/; domain=.google.com; Secure; SameSite=none, NID=216=muxQNHctgg_aUPrNkB2H4O1TrzUSBRq_Xnk2dzmHxxsRDmlfDDRopv-8rBF4Z_oFIMQNGTBGdtH_OjR6741hSC-d6C4dgbcG29Aq6JyESWQn__fqbwmaeqmko3-tDZ7mRTkgaEICBHACMqcb9acXAjkty5U7jpUknShM4KoyYL4; expires=Thu, 18-Nov-2021 19:39:07 GMT; path=/; domain=.google.com; Secure; HttpOnly; SameSite=none
	Alt-Svc: h3-29=":443"; ma=2592000,h3-T051=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
	Transfer-Encoding: chunked

**Comment by ricardolopes86** [comment]
Started to have the same issue a few minutes ago.

**Comment by masterandservant** [comment]
[19/May/2021 23:43:53] Last request done:
	URL: https://www.google.com/?q=Why+is+stealing+wrong
	DATA: None
	OTHERS: {}

	200
	Date: Wed, 19 May 2021 21:43:53 GMT
	Expires: -1
	Cache-Control: private, max-age=0
	Content-Type: text/html; charset=UTF-8
	Strict-Transport-Security: max-age=31536000
	BFCache-Opt-In: unload
	P3P: CP="This is not a P3P policy! See g.co/p3phelp for more info."
	Content-Encoding: gzip
	Server: gws
	X-XSS-Protection: 0
	X-Frame-Options: SAMEORIGIN
	Set-Cookie: CONSENT=PENDING+274; expires=Fri, 01-Jan-2038 00:00:00 GMT; path=/; domain=.google.com; Secure
	Alt-Svc: h3-29=":443"; ma=2592000,h3-T051=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
	Transfer-Encoding: chunked


very funny, haha, very funny...

**Comment by mavalderrama** [comment]
same here

**Comment by vkhoilq** [comment]
+1 hahaha

**Comment by jernkuan** [comment]
Try changing the user agent in the header of safaribooks.py to 

"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36",

**Comment by mavalderrama** [comment]
> Try changing the user agent in the header of safaribooks.py to
> 
> "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36",

this worked for me thanks

**Comment by vkhoilq** [comment]
worked for me too, tks

**Comment by lorenzodifuccia** [comment]
Let's try c872f22...

**Comment by mavalderrama** [comment]
> Let's try [c872f22](https://github.com/lorenzodifuccia/safaribooks/commit/c872f22f29e2432af5a9372272a5535e64790d2c)...

thanks, this commit fixed the problem

**Comment by chel034** [comment]
thanks, this problem is fixed, I close issue.

**Comment by Bomberdash** [comment]
Thank you mavalderrama! It working

**Comment by standurside** [comment]
thanx so much, It Worked.
