### ISSUE TITLE
Error: [#] Unhandled Exception: 'next' (type: KeyError)

### ISSUE THREAD

**Issue by MKentV** [lorenzodifuccia/safaribooks#269]
Suddenly getting this error - worked until yesterday. Very odd.

**Comment by MKentV** [comment]
Apologies this appears to be a dupe of #189

**Comment by henryjoshuasmith** [comment]
I'm also getting this error. Worked fine last week.

**Comment by scotia70** [comment]
I too.  The log file shows a redirect:
`20/May/2021 16:58:30]   File "./safaribooks.py", line 1112, in <module>
    SafariBooks(args_parsed)
  File "./safaribooks.py", line 335, in __init__
    self.do_login(*args.cred)
  File "./safaribooks.py", line 471, in do_login
    next_parameter = parse_qs(urlparse(response.request.url).query)["next"][0]

[20/May/2021 16:58:30] Unhandled Exception: 'next' (type: KeyError)
[20/May/2021 16:58:30] Last request done:
        URL: https://www.google.com/?q=Why+is+stealing+wrong
        DATA: None
        OTHERS: {}

        200
        Date: Thu, 20 May 2021 06:58:29 GMT
        Expires: -1
        Cache-Control: private, max-age=0
        Content-Type: text/html; charset=UTF-8
        Strict-Transport-Security: max-age=31536000
        BFCache-Opt-In: unload
        P3P: CP="This is not a P3P policy! See g.co/p3phelp for more info."
        Content-Encoding: gzip
        Server: gws
        X-XSS-Protection: 0
        X-Frame-Options: SAMEORIGIN`

**Comment by chel034** [comment]
duplicate #268

**Comment by eurubkov** [comment]
Just ran into this myself. Looks like it was fixed by pulling the latest master version. Thanks!
