### ISSUE TITLE
I can't set the program up

### ISSUE THREAD

**Issue by IronLover64** [lorenzodifuccia/safaribooks#278]
I typed git clone https://github.com/lorenzodifuccia/safaribooks.git into cmd and I get an error:
'git' is not recognized as an internal or external command,
operable program or batch file.

**Comment by Father-Stalin** [comment]
Hello comrade, you'll have to install git first via your distro's package manager. For instance on my ubuntu instance, I type 

sudo apt-get install git

and then you can use git. For more documentation, please see https://git-scm.com/book/en/v2/Getting-Started-Installing-Git
