### ISSUE TITLE
Not working on some books

### ISSUE THREAD

**Issue by yingfu** [lorenzodifuccia/safaribooks#29]
python 3.7.0 for macOS
errors alway on `ch02.html`

Books URL:
https://www.safaribooksonline.com/library/view/learning-swift-3rd/9781491987568/
https://www.safaribooksonline.com/library/view/you-dont-know/9781491905241/

error info:
`[-] URL: https://www.safaribooksonline.com/library/view/learning-swift-3rd/9781491987568/
[*] Retrieving book chapters...
[*] Output directory:
    /safaribooks/Books/Learning Swift 3rd Edition (9781491987568)
[-] Downloading book contents... (32 chapters)
[#] Parser: book content's corrupted or not present: ch02.html (2. The Swift Programming Language)
[+] Please delete all the `<BOOK NAME>/OEBPS/*.xhtml` files and restart the program.
[!] Aborting...`

`[-] URL: https://www.safaribooksonline.com/library/view/you-dont-know/9781491905241/
[*] Retrieving book chapters...
[*] Output directory:
    /safaribooks/Books/You Don_t Know JS (9781491905241)
[-] Downloading book contents... (17 chapters)
[#] Parser: book content's corrupted or not present: ch02.html (2. Syntax)
[+] Please delete all the `<BOOK NAME>/OEBPS/*.xhtml` files and restart the program.
[!] Aborting...`

**Comment by lorenzodifuccia** [comment]
Could you please send me the output of these two commands?
```bash
pip3 freeze
```

```bash
python3 --version
```

Thanks

**Comment by yingfu** [comment]
python3 version 3.7.0

pip3 freeze:
asn1crypto==0.24.0
beautifulsoup4==4.6.0
certifi==2017.11.5
cffi==1.11.5
chardet==3.0.4
cryptography==2.3
idna==2.7
lxml==4.2.3
prawcore==1.0.0
pycparser==2.18
requests==2.19.1
six==1.11.0
update-checker==0.16
urllib3==1.23

**Comment by lorenzodifuccia** [comment]
Did you try again from the issue opening?

**Comment by rtuttlecoder** [comment]
same thing is happening with me too

**Comment by Kambaa** [comment]
after trying a couple of times, it worked for me.

**Comment by andreshincapier** [comment]
I have the same issue when I try to get this book 9781789801217, I recive this message
` Parser: book content's corrupted or not present: d38fed87-784d-4c0e-a43a-092345d6d109.xhtml (Representations of graphs)`

I have this pip version pip 21.2.4, and I have MacOs Big sur v 11.5.1 with M1 chip

But when I try to get this book from another Mac with intel and MacOs Bigsur 11.6 and older version of pip woks perfec

**Comment by sontek** [comment]
I had the same issue on my M1 mac, for some reason switching to the beautiful soup parser worked so thats what I'm using:

https://github.com/lorenzodifuccia/safaribooks/compare/master...sontek:m1-mac?expand=1
