### ISSUE TITLE
Images are broken when downloaded

### ISSUE THREAD

**Issue by eggfluid** [lorenzodifuccia/safaribooks#299]
I tried to down books like [this](https://learning.oreilly.com/library/view/pixel-art-for/9781482252316/) and [this](https://learning.oreilly.com/library/view/refactoring-improving-the/9780134757681/).
It downloads everything correctly, but it seems like all the png files in images folder are broken. 
<img width="251" alt="Screen Shot 2021-11-14 at 12 25 05 PM" src="https://user-images.githubusercontent.com/94320343/141697402-badfd620-f15b-4733-bc06-84c425f332a7.png">
Above is what I see when I click the png files in Images folder. I tried to open them in a browser as well, and I just see a white rectangle.
<img width="49" alt="Screen Shot 2021-11-14 at 12 30 15 PM" src="https://user-images.githubusercontent.com/94320343/141697526-333d968f-c400-4b92-93fa-b6e80d0d14cb.png">
Above is what I see when I open the image on a browser.
Lastly, the size of images are all the same with 28KB.
Anyone having a similar issue? Any fixes for this?

**Comment by 0Ky** [comment]
The second book you've mentioned doesn't contain any .png files and there's no issues with any of the .png files in the first book you've mentioned. Are you using the latest commit of safaribooks? Can you post the log output using `--preserve-log` option?

**Comment by eggfluid** [comment]
@0Ky Thanks for the tip! I thought I had the latest commit of Safaribooks, but it turned out I didn't. Using the latest commit completely solved the issue with the second one. With the first one, it now downloads the images, but it doesn't properly load the images. Below is what I see: 
<img width="1058" alt="Screen Shot 2021-11-15 at 2 34 16 PM" src="https://user-images.githubusercontent.com/94320343/141863454-6e99c166-8681-45a0-8af6-6a0b61fb2808.png">

Also, here is the log file:
[info_9781482252316.log](https://github.com/lorenzodifuccia/safaribooks/files/7542032/info_9781482252316.log)

**Comment by 0Ky** [comment]
That's most likely related to CSS. Also, safaribooks doesn't download custom fonts used by the book, which is why you'll see missing characters. If you're using Calibre, hit 'T' to edit the book and look at the file preview, it's an effortless workaround to the overlapping texts. I was unable to fix the overlapping texts by exporting it to pdf, maybe an easier way would be to view the chapter files directly from a browser?

**Comment by eggfluid** [comment]
Yeah, opening the book with Calibre by hitting 'T' helped with overlapping texts. I guess I just need to find a proper font for missing characters and a way to get rid of overlapping texts :\
