### ISSUE TITLE
Add info to readme about ORLY_BASE_HOST for SSO

### ISSUE THREAD

**Issue by fredlarochelle** [lorenzodifuccia/safaribooks#304]
As said in the title, info should be added to the readme about a possible reason why SSO might not be working for some folks. In my case, the URL was different than "oreilly.com". I simply changed the value of ORLY_BASE_HOST (line 24 of safaribooks.py) to the correct URL and it started working. 

Should I make a pull request for such a simple change to the readme?

**Comment by lorenzodifuccia** [comment]
I think that for SSO is better what said until now: "use authenticated cookie".
See: [README](https://github.com/lorenzodifuccia/safaribooks#:~:text=called%20cookies.json.-,For%20SSO,-%2C%20please%20use%20the), https://github.com/lorenzodifuccia/safaribooks/issues/150#issuecomment-555423085

If you don't agree, please reopen this issue!

**Comment by esmail** [comment]
I think what OP is saying is that in some cases you're not logging into "oreilly.com" and it would be good to have documentation on how to modify things accordingly.

In my case (accessing O'Reilly through my public library), both `SAFARI_BASE_HOST` and `API_ORIGIN_HOST` had to be set to "learning-oreilly-com.opl.idm.oclc.org", and I had to remove the "www" from `ORLY_BASE_URL`.
