### ISSUE TITLE
Unable To Retrieve book Chapters Issue

### ISSUE THREAD

**Issue by negmos** [lorenzodifuccia/safaribooks#306]
Hi All,

I was trying to download a book "9781119621492" which i actually downloaded before, but for some reason im getting the error:
"API: Unable to retrieve book chapters"

I have pulled the latest code but still same issue.

**Comment by Korred** [comment]
@negmos - Can you please check again? It looks fine on my end.

![grafik](https://user-images.githubusercontent.com/1658897/150547017-26d8755e-7372-4f51-bb17-c6c80ae664bc.png)

**Comment by negmos** [comment]
i tried now with fresh version of the repo, and it works.. looks like i had some local problem
