### ISSUE TITLE
No images downloaded

### ISSUE THREAD

**Issue by richardxy** [lorenzodifuccia/safaribooks#31]
Thanks for the good work! The code works, but all the images are missing in the book. Please advise how to address the problem. Thanks!

**Comment by lorenzodifuccia** [comment]
Could you please send me the book's ID?

**Comment by richardxy** [comment]
I retried it today and it worked. It must have something to do with Safari connectivity at that time. Sorry and thanks.

**Comment by lorenzodifuccia** [comment]
Ok. Perfect!!
