### ISSUE TITLE
Downloading from public library providing Oreilly subscription

### ISSUE THREAD

**Issue by sandarbhasthana** [lorenzodifuccia/safaribooks#313]
I'm a member of Sunnyvale Public Library and have a subscription to Oreilly, I have downloaded the tool but currently, it only serves the base URL:  **safaribooksonline.com/library/views/book_name**
whereas the Sunnyvale URL is: **0-learning-oreilly-com.milcat.sunnyvalelibrary.org/library/view/book_name**
Is there a way I can replace the base URL and download it from the above link? 
Also the library login:pass is: **lib_card_number:pass**

Thanks!

**Comment by lorenzodifuccia** [comment]
Search SSO on README and in the isssues
