### ISSUE TITLE
Images from books are corrupt

### ISSUE THREAD

**Issue by jgarr16** [lorenzodifuccia/safaribooks#314]
All of the images that are being retrieved from O'Reilly are corrupt. I have tried several books over the course of several days; the only image that downloads in a usable format is the default_cover.jpeg. Other than that, several hundred *.jpg files cannot be opened with any application (i.e., image apps or text apps). 

Examples: 
https://learning.oreilly.com/library/view/principles-of-computer/9781260474329/
https://learning.oreilly.com/library/view/mike-meyers-comptia/9781260473704/
https://learning.oreilly.com/library/view/mike-meyers-comptia/9781260467963/

The images download something, but the .jpg files are all the same size (29KB in every case) and do not resolve in the resultant .epub. When I try to open any of the .jpg files with various imaging applications, I get an error that looks like this:
 - The file “F07-02.jpg” could not be opened. It may be damaged or use a file format that Preview doesn’t recognize
<img width="260" alt="safaribooks_error" src="https://user-images.githubusercontent.com/15323251/157605988-8c3d921e-3d84-4673-9360-624fdcb67b46.png">
.

**Comment by palash247** [comment]
I had the same issue which got resolved after pulling the latest code.

**Comment by lramosduarte** [comment]
then it's working?

> I had the same issue which got resolved after pulling the latest code.

**Comment by jgarr16** [comment]
@palash247 - thanks; latest version cured all.
@lramosduarte  - yes, it's working perfectly.
@lorenzodifuccia - thanks for what you do! Amazing!
