### ISSUE TITLE
Auth Failure. - Unexpected error!

### ISSUE THREAD

**Issue by MatterSec** [lorenzodifuccia/safaribooks#315]
Error when trying to download books/logging in.

[-] Logging into Safari Books Online...                                                                  
[#] Login: unable to perform auth login to Safari Books Online.                                          
[*] Details:
    Unexpected error!
[!] Aborting...    

I've tried downloading latest version from git and deleted all files. Any ideas what could be causing this, can access the internet etc.
Thanks

**Comment by ntlzz93** [comment]
the same with me

**Comment by sankalpgaikwad** [comment]
> Error when trying to download books/logging in.
> 
> [-] Logging into Safari Books Online... [#] Login: unable to perform auth login to Safari Books Online. [*] Details: Unexpected error! [!] Aborting...
> 
> I've tried downloading latest version from git and deleted all files. Any ideas what could be causing this, can access the internet etc. Thanks

Same here

**Comment by erymack** [comment]
Hi,
When I used my acm.org account to log into Safari Books Online an error appears:

[-] Logging into Safari Books Online...
[#] Login: unable to perform auth login to Safari Books Online.
[*] Details:
Unexpected error!
[!] Aborting...

But when used 14-days trial account which I set up on the O'Reilly website for testing then everything is fine.
Thank you
