### ISSUE TITLE
flask3.9  ImportError: cannot import name 'escape' from 'jinja2'

### ISSUE THREAD

**Issue by sbulink** [lorenzodifuccia/safaribooks#318]
Hi I'm suddenly getting this error:
has anything happened to flask3.9, \Python\Python39\lib\site-packages\flask_init_.py", line 14, in
from jinja2 import escape
ImportError: cannot import name 'escape' from 'jinja2'

**Comment by rufanov** [comment]
This project don't use flask or jinja2, so this is just problem with python installed on your machine.
