### ISSUE TITLE
Unhandled Exception: 'rights' (type: KeyError)

### ISSUE THREAD

**Issue by mukuntharajaa** [lorenzodifuccia/safaribooks#326]
I see this error in master (4aa27f0c6bdf393090856a07c955a65b10841e74) version of this repository. Please let me know how to fix ?

![Screenshot from 2022-09-28 12-52-52](https://user-images.githubusercontent.com/19199981/192749520-fc522e75-e9ee-435d-bdf9-485df9232317.png)

Some information about my environment.

cat /etc/os-release
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"

python3 --version
Python 3.10.6

**Comment by rufanov** [comment]
Update it. You are literally using super-old code from one of first commits from 2020..
