### ISSUE TITLE
Trial account not working due to email issue

### ISSUE THREAD

**Issue by profmancusoa** [lorenzodifuccia/safaribooks#327]
hello,
this is not a issue of the tool. This is more a request to check whether other people are experiencing the same issue I am facing

When I try to get a free temporary trial account I get an issue on the email addres sI provide

is anyone experiencing something similar?

Thnx

![image](https://user-images.githubusercontent.com/111191978/194957267-093b33de-b256-4596-bfe9-54c8813129ea.png)

**Comment by ivanpagac** [comment]
try to use random gmail address - some name.surname, guess some, lot of temp email services stopped working with oreilly

**Comment by profmancusoa** [comment]
indeed your suggestion does work. thank you so much
