### ISSUE TITLE
Could you create Mobipocket eBook (.mobi) file?

### ISSUE THREAD

**Issue by banv** [lorenzodifuccia/safaribooks#34]
Thank you for creating epub file!
But it would be wonderful if you could create a .mobi file, too. So I can read it on my Kindle.
Thank so much!

**Comment by lorenzodifuccia** [comment]
Hi @banv,
I'm sorry but this isn't the purpose of this program.
As I wrote in the `README`, you can use [Calibre](https://calibre-ebook.com/) to accomplish your request.
Follow the instruction on the [`README`](https://github.com/lorenzodifuccia/safaribooks/blob/master/README.md), Line 80:

> The program default options are thought for...
