### ISSUE TITLE
Generate to pdf

### ISSUE THREAD

**Issue by Spri85** [lorenzodifuccia/safaribooks#35]
Hello Lorenzo,
First of all thank you for this great app!

Is it possible to add feature of loading books directly to pdf format?
It would be very helpful.

**Comment by mayqueen91** [comment]
I would also appreciate this feature.

**Comment by mohseneslami** [comment]
Is possible for Make PDF?

**Comment by lorenzodifuccia** [comment]
Use Calibre to convert the EPUB to every format you want!
