### ISSUE TITLE
Only book cover image is downloaded. Other book images are not downloaded and available in epub file.

### ISSUE THREAD

**Issue by amitfegade121** [lorenzodifuccia/safaribooks#36]

**Comment by lorenzodifuccia** [comment]
Did you restart the program without deleting the old book directory?

**Comment by amitfegade121** [comment]
Sorry, I haven't deleted it. After deleting, its working perfectly fine.

**Comment by lorenzodifuccia** [comment]
_All's well that ends well..._ :smile:
