### ISSUE TITLE
Infinite "Creating EPUB file..." + fill filesystem

### ISSUE THREAD

**Issue by neogta** [lorenzodifuccia/safaribooks#4]
Hello (me again)
once again, thank you for this script, it's really useful !
I'm using it to prepare some certifications at work and have a valid Safari account.

A) For some books it works perfectly ( 9781449342562 or the Python example you give)
B) For some, it seems to loop somewhere in the zipping process and create a X GB file and crashes because of space issue at one point, 
for example 9780134466330 or 9780134030999

C) I tried debugging and issue seems to be here : 
shutil.make_archive(zip_file, 'zip', self.BOOK_PATH)

D) I guess it's because of the title of these books which contains a whole lot of special character

E) I tried to workaround by zipping the "Ebook Path" folder and renaming to epub and it works :)
I imagine the solution / workaround could be to allow to generate the "epub" filename with "book id" instead of book_path

F) Also when opening an epub generated by this script, it contains : 
folders : 
META-INF
OEBPS

Files : 
mimetype
<bookname>.zip
which also contains empty folders META-INF and OEBPS + mimetype

So I'd guess not needed

Have a great day !

**Comment by lorenzodifuccia** [comment]
Ok, thanks so much for the issue and for the help!
I tried to fix all the problems. Try it out and let me know.
