### ISSUE TITLE
allow_abbrev error

### ISSUE THREAD

**Issue by cybercorp31** [lorenzodifuccia/safaribooks#41]
Hello

Whenever I try to run it, it shows the following error:

Traceback (most recent call last):
  File "safaribooks.py", line 983, in <module>
    allow_abbrev=False)
TypeError: __init__() got an unexpected keyword argument 'allow_abbrev'

My python version:    Python 3.4.3

**Comment by lorenzodifuccia** [comment]
This is a duplicate issue.
Please read #14
