### ISSUE TITLE
error trying to retrieve this page / Exception: Expecting value

### ISSUE THREAD

**Issue by gonciarz** [lorenzodifuccia/safaribooks#44]
info_9781617292774.log
`error trying to retrieve this page: kindle_split_016.html (Chapter 7. Shaping the relevance function)\n   
`
info_9781782161363.log
`error trying to retrieve this page: ch02s06.html (Summary)`

info_9781783984923.log
`Unhandled Exception: Expecting value: line 2 column 1 (char 1) (type: JSONDecodeError)'`

info_9781783987023.log
`error trying to retrieve this page: ch04s03.html (Built-in analyzers)
`
info_9781784391010.log
`error trying to retrieve this page: ch03s08.html (Sorting your data)\n    
`
info_9781784399641.log
`error trying to retrieve this page: toc.html (Table of Contents)
`
info_9781786460011.log
`b'Unhandled Exception: Expecting value: line 2 column 1 (char 1) (type: JSONDecodeError)'
`
info_9781786460189.log
`b'Unhandled Exception: Expecting value: line 2 column 1 (char 1) (type: JSONDecodeError)'
`
info_9781787128453.log
`error trying to retrieve this page: 051e3348-bdf0-47dc-b558-0f2be7fbb674.xhtml (Boolean)\n    
`
info_9781787281868.log
`b'Unhandled Exception: Expecting value: line 2 column 1 (char 1) (type: JSONDecodeError)'
`
info_9781787286849.log
`error trying to retrieve this page: 75d192b4-d51a-48e9-b3f8-798eb58c3e35.xhtml (There's more...)\n    
`
info_9781787288546.log
`error trying to retrieve this page: ch13.html (3. Not Only Full Text Search)\n    `

info_9781788837385.log
`error trying to retrieve this page: cdd9d5a0-5524-4b2a-b760-c8270f85cb94.xhtml (Production Solr setup)\n`

Please let me know if you need log files. I may send them in a secure channel because they contain sensitive data.

**Comment by lorenzodifuccia** [comment]
I can't handle this now, I'm too busy with work.
Try to delete the sensible information and paste logs here, maybe some good Samaritan will help you (and me).
