### ISSUE TITLE
Download Not Successful for a special book

### ISSUE THREAD

**Issue by lazypareto** [lorenzodifuccia/safaribooks#45]
[-] Release Date: 2018-06-27                                                           
[-] URL: https://www.safaribooksonline.com/library/view/mastering-machine-learning/9781788997409/
[*] Retrieving book chapters...                                                        
[#] HTTPSConnectionPool(host='www.safaribooksonline.com', port=443): Max retries exceeded with url: /api/v1/book/9781788997409/chapter/?page=19 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb5d689ac>: Failed to establish a new connection: [Errno -2] Name or service not known',))
[#] API: unable to retrieve book chapters.                                             
[+] Please delete all the `<BOOK NAME>/OEBPS/*.xhtml` files and restart the program.   
[!] Aborting... 

Book ID: 9781788997409

**Comment by lazypareto** [comment]
[*] Retrieving book chapters...                                                        
[*] Output directory:                                                                  
    /root/Documents/safaribooks/Books/Mastering Machine Learning for Penetration Testing (9781788997409)
[-] Downloading book contents... (209 chapters)                                        
[#] HTTPSConnectionPool(host='www.safaribooksonline.com', port=443): Max retries exceeded with url: /library/view/mastering-machine-learning/9781788997409/49fd21a4-2a61-41bd-b304-862081d3fccb.xhtml (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb5dc252c>: Failed to establish a new connection: [Errno -2] Name or service not known',))
[#] Crawler: error trying to retrieve this page: 49fd21a4-2a61-41bd-b304-862081d3fccb.xhtml (Linear regression&#xA0;)
    From: https://www.safaribooksonline.com/library/view/mastering-machine-learning/9781788997409/49fd21a4-2a61-41bd-b304-862081d3fccb.xhtml
[+] Please delete all the `<BOOK NAME>/OEBPS/*.xhtml` files and restart the program.   
[!] Aborting...

**Comment by lorenzodifuccia** [comment]
`NewConnectionError` it seems that was a Connection Error.... :stuck_out_tongue_winking_eye: 
Did you try again?
