### ISSUE TITLE
error on login

### ISSUE THREAD

**Issue by billhongs** [lorenzodifuccia/safaribooks#48]
Login: no CSRF Token found in the page. Unable to continue the login. Try again...

**Comment by Kambaa** [comment]
same here!

![image](https://user-images.githubusercontent.com/5601326/49210502-4b7b8980-f3ce-11e8-9519-9f7d5b5f19d1.png)

**Comment by AldoMX** [comment]
They replaced the homepage, try using a cookie in the meantime.

**Comment by infosisio** [comment]
Same error here, was about to create a new issue.

**Comment by Kambaa** [comment]
By removing the --cred parameter and filling the cookies.json file as the example you've given. i was able to continue snorting :) thank you.

**Comment by psaditya** [comment]
I pasted cookies.json file into the installation directory i.e. safaribooks. I am using macbook. When I remove --cred parameter and run it then it gives me error message[#] API: Out-of-Session (Authentication credentials were not provided.). If use the --cred parameter then it gives me CSRF token error. Not sure what I am doing wrong here. Can someone help please.

**Comment by Kambaa** [comment]
You need to enter the website one time, and replace the cookies.json file fields according to your browsers cookie. In my computer, i opened the website and opened the devtools and get the information like this: 
![image](https://user-images.githubusercontent.com/5601326/49288423-bb167500-f4b1-11e8-969b-7102dbbd79b5.png)


You see the names, check the names in the cookies.json file and replace values in your browser

**Comment by yaasin12** [comment]
same problem. Anyone can help me with using the cookies file?

**Comment by yaasin12** [comment]
API: Out-of-Session (You do not have permission to perform this action.). I got this error when i used the cookies.json

**Comment by bpiec** [comment]
There is already a great hint for that: https://github.com/lorenzodifuccia/safaribooks/issues/2#issuecomment-429343521

**Comment by sarcastic** [comment]
Just update the requested login 

On line 420

```python
    def do_login(self, email, password):
        response = self.requests_provider(self.LOGIN_URL)
```

**Comment by yaasin12** [comment]
> Just update the login url
> 
> On line 420
> 
> ```python
>     def do_login(self, email, password):
>         response = self.requests_provider(self.LOGIN_URL)
> ```

I still don't get it, sorry i'm a noob

**Comment by yaasin12** [comment]
> There is already a great hint for that: [#2 (comment)](https://github.com/lorenzodifuccia/safaribooks/issues/2#issuecomment-429343521)

I was just using an expired account, my bad xD sorry and thanks

**Comment by billhongs** [comment]
Thanks a lot.

**Comment by hbakhtiyor** [comment]
i tried, but nothing works
[#] API: Out-of-Session (You do not have permission to perform this action.).

**Comment by yaasin12** [comment]
Your account subscription is inactive. I created another one and it's working fine for me.

**Comment by infosisio** [comment]
@billhongs It may be a good idea to open the issue again, so that the author can keep track of it and do something about it.
