### ISSUE TITLE
problem install safaribooks

### ISSUE THREAD

**Issue by mohseneslami** [lorenzodifuccia/safaribooks#49]
Hello,

When i want install safaribooks in python3

C:\safaribooks>pip3 install -r requirements.txt
Requirement already satisfied: lxml>=4.1.1 in c:\python\lib\site-packages (from -r requirements.txt (line 1)) (4.2.5)
Requirement already satisfied: requests>=2.20.0 in c:\python\lib\site-packages (from -r requirements.txt (line 2)) (2.20.1)
Requirement already satisfied: certifi>=2017.4.17 in c:\python\lib\site-packages (from requests>=2.20.0->-r requirements.txt (line 2)) (2018.11.29)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in c:\python\lib\site-packages (from requests>=2.20.0->-r requirements.txt (line 2)) (1.24.1)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\python\lib\site-packages (from requests>=2.20.0->-r requirements.txt (line 2)) (3.0.4)
Requirement already satisfied: idna<2.8,>=2.5 in c:\python\lib\site-packages (from requests>=2.20.0->-r requirements.txt (line 2)) (2.7)

C:\safaribooks>pip list
Package    Version
---------- ----------
certifi    2018.11.29
chardet    3.0.4
idna       2.7
lxml       4.2.5
pip        18.1
requests   2.20.1
setuptools 40.6.2
urllib3    1.24.1
youtube-dl 2018.11.23

How solve it ?

**Comment by mohseneslami** [comment]
no answer me?

**Comment by liskin** [comment]
That means the requirements were installed, now just run `python3 safaribooks.py`.

**Comment by lorenzodifuccia** [comment]
`safaribooks.py` is a script, it doesn't install to your system. You have to run it manually anytime you want. Is this the problem?

**Comment by mohseneslami** [comment]
can tell me How install safaribooks.py ? and Then How Use it ?

I Run in CMD : python3 safaribooks.py

'python3' is not recognized as an internal or external command,
operable program or batch file.

**Comment by lorenzodifuccia** [comment]
`safaribooks.py` is a [script](https://en.wikipedia.org/wiki/Script), it doesn't install to your system. You have to run it manually anytime you want.

Now:
 - You installed Python3 on your system (I assert this because I can see the script output runned by `python safaribooks.py`). Are you with me? You can run it in CMD simply typing: `python safaribooks.py`.
- The script output says: `safaribooks.py: error: the following arguments are required: <BOOK ID>`. That's because you ~don't read the README file~ didn't specified any Book ID. Try to specify the ID of the book you would to download. Ok?

Let me know!

**Comment by LingarajBagali** [comment]
Just run like `python <script and its options>` it will work.

**Comment by mohseneslami** [comment]
Please help me ... i try for downoad a book from this Command

safaribooks.py --cred "myemail@gmail.com:12345678" 9781617294808 tell me error

Traceback (most recent call last):
  File "C:\safaribooks\safaribooks.py", line 9, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by mohseneslami** [comment]
no help?

**Comment by lorenzodifuccia** [comment]
Could you please paste the output of these three commands? Please, run each line individually.
`where python`
`python --version`
`pip --version`

Thanks!

**Comment by mohseneslami** [comment]
C:\Users\Administrator>where python
C:\Python\python.exe

C:\Users\Administrator>python --version
Python 3.7.1

C:\Users\Administrator>pip --version
pip 19.0.3 from c:\python\lib\site-packages\pip (python 3.7)

**Comment by lorenzodifuccia** [comment]
Ok, thanks.
Now:

`pip install --ignore-installed -r requirements.txt`

`pip list`

`python safaribooks.py xxxxxxxx`

**Comment by mohseneslami** [comment]
Thank you. I did this three command

but still can't download ebook from safari

I use this command after pip list:

First Command:
C:\safaribooks>pip install --ignore-installed -r requirements.txt
Collecting lxml>=4.1.1 (from -r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/5c/da/ca09ea03677a9f7f9c8c7f290990792a5ee340f6c88460dca9333c58124e/lxml-4.3.3-cp37-cp37m-win32.whl (3.2MB)
    100% |████████████████████████████████| 3.3MB 2.2MB/s
Collecting requests>=2.20.0 (from -r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/7d/e3/20f3d364d6c8e5d2353c72a67778eb189176f08e873c9900e10c0287b84b/requests-2.21.0-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests>=2.20.0->-r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting urllib3<1.25,>=1.21.1 (from requests>=2.20.0->-r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/df/1c/59cca3abf96f991f2ec3131a4ffe72ae3d9ea1f5894abe8a9c5e3c77cfee/urllib3-1.24.2-py2.py3-none-any.whl (131kB)
    100% |████████████████████████████████| 133kB 3.3MB/s
Collecting certifi>=2017.4.17 (from requests>=2.20.0->-r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/60/75/f692a584e85b7eaba0e03827b3d51f45f571c2e793dd731e598828d380aa/certifi-2019.3.9-py2.py3-none-any.whl (158kB)
    100% |████████████████████████████████| 163kB 6.6MB/s
Collecting idna<2.9,>=2.5 (from requests>=2.20.0->-r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/14/2c/cd551d81dbe15200be1cf41cd03869a46fe7226e7450af7a6545bfc474c9/idna-2.8-py2.py3-none-any.whl (58kB)
    100% |████████████████████████████████| 61kB 2.0MB/s
Installing collected packages: lxml, chardet, urllib3, certifi, idna, requests
Could not install packages due to an EnvironmentError: [WinError 5] Access is denied: 'c:\\python\\Lib\\site-packages\\lxml\\builder.cp37-win32.pyd'
Consider using the `--user` option or check the permissions.

You are using pip version 19.0.3, however version 19.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
Second Command:
C:\safaribooks>pip list
Package    Version
---------- ----------
certifi    2018.11.29
chardet    3.0.4
idna       2.7
lxml       4.2.5
pip        19.0.3
requests   2.21.0
setuptools 40.6.2
urllib3    1.24.1
youtube-dl 2019.3.18
You are using pip version 19.0.3, however version 19.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
Three command
safaribooks.py --cred "myemail:mypassword" 9781617294808

**Comment by lorenzodifuccia** [comment]
From the second command it seems that the `requests` module is correctly installed.
Because you don't attached the output of the third command, please paste it or run the following:
```bash
C:\safaribooks> python
Python ...
...
Type "help", "copyright", "credits" or "license" for more information.
>>> import requests
```
---

Bonus: pip installation went in error. Try to run with the `--user` flag.
`pip install --user --ignore-installed -r requirements.txt`

**Comment by mohseneslami** [comment]
C:\safaribooks>safaribooks.py --cred "myemail:mypassword" 9781617294808
Traceback (most recent call last):
  File "C:\safaribooks\safaribooks.py", line 11, in <module>
    from lxml import html, etree
  File "C:\Users\Administrator\AppData\Roaming\Python\Python37\site-packages\lxml\html\__init__.py", line 53, in <module>
    from .. import etree
ImportError: cannot import name 'etree' from 'lxml' (C:\Users\Administrator\AppData\Roaming\Python\Python37\site-packages\lxml\__init__.py)

=================

C:\safaribooks>python
Python 3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 14:05:16) [MSC v.1915 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import requests
>>>

when try for enter import requests " just enter to empty line and no error

=================

C:\safaribooks>pip install --user --ignore-installed -r requirements.txt
Collecting lxml>=4.1.1 (from -r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/5c/da/ca09ea03677a9f7f9c8c7f290990792a5ee340f6c88460dca9333c58124e/lxml-4.3.3-cp37-cp37m-win32.whl
Collecting requests>=2.20.0 (from -r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/7d/e3/20f3d364d6c8e5d2353c72a67778eb189176f08e873c9900e10c0287b84b/requests-2.21.0-py2.py3-none-any.whl
Collecting urllib3<1.25,>=1.21.1 (from requests>=2.20.0->-r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/df/1c/59cca3abf96f991f2ec3131a4ffe72ae3d9ea1f5894abe8a9c5e3c77cfee/urllib3-1.24.2-py2.py3-none-any.whl
Collecting idna<2.9,>=2.5 (from requests>=2.20.0->-r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/14/2c/cd551d81dbe15200be1cf41cd03869a46fe7226e7450af7a6545bfc474c9/idna-2.8-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests>=2.20.0->-r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests>=2.20.0->-r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/60/75/f692a584e85b7eaba0e03827b3d51f45f571c2e793dd731e598828d380aa/certifi-2019.3.9-py2.py3-none-any.whl
Installing collected packages: lxml, urllib3, idna, chardet, certifi, requests
  The script chardetect.exe is installed in 'C:\Users\Administrator\AppData\Roaming\Python\Python37\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed certifi-2019.3.9 chardet-3.0.4 idna-2.8 lxml-4.3.3 requests-2.21.0 urllib3-1.24.2
You are using pip version 19.0.3, however version 19.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

C:\safaribooks>

**Comment by lorenzodifuccia** [comment]
If after the last command (`pip install...`) it still doesn't work I don't know which is the problem with your Python. Try to download `pipenv` or `virtualenv` and redo the commands.
If the error continues to be related to lxml, try to remove and install it back [[source](https://stackoverflow.com/questions/53406638/importerror-cannot-import-name-etree-on-python-3-6)].

**Important**: this issue is not related to the program but to your personal python environment. This issue should be closed but I want to leave it opened only to help you.

Try by yourself to do some *problem solving* googling the error you encountered.

**Comment by mohseneslami** [comment]
I uninstalled and Again installed python 3.7 and my problem solved . Now i download ebook ... Thank you for your help

**Comment by lorenzodifuccia** [comment]
Good!! Closing the issue.

**Comment by d3xt3r2909** [comment]
`pip3 install requests` just install specific module and it will work
