### ISSUE TITLE
API: Out-of-Session (Authentication credentials were not provided.)

### ISSUE THREAD

**Issue by suniltpn** [lorenzodifuccia/safaribooks#5]
I am getting this error after Retrieving book info message. How can I fix this?

**Comment by suniltpn** [comment]
This is the complete log
[24/Feb/2018 03:04:02] ** Welcome to SafariBooks! **
[24/Feb/2018 03:04:02] Logging into Safari Books Online...
[24/Feb/2018 03:04:07] Retrieving book info...
[24/Feb/2018 03:04:08] API: Out-of-Session (Authentication credentials were not provided.).

**Comment by lorenzodifuccia** [comment]
Could you retry? Pull the last version of the program, I added some function for log verbosity.

**Comment by franTarkenton** [comment]
I'm getting the same error, here is what is included in the log:
`[12/Mar/2018 15:03:08] ** Welcome to SafariBooks! **
[12/Mar/2018 15:03:08] Logging into Safari Books Online...
[12/Mar/2018 15:03:10] Retrieving book info...
[12/Mar/2018 15:03:11] API: Out-of-Session (Authentication credentials were not provided.).

[12/Mar/2018 15:03:11] Last request done:
	URL: https://www.safaribooksonline.com/api/v1/book/9781680502848/
	DATA: None
	OTHERS: {}

	401
	Server: nginx/1.10.3 (Ubuntu)
	Content-Type: application/json
	Content-Language: en-US
	X-Frame-Options: SAMEORIGIN
	x-xss-protection: 1; mode=block
	WWW-Authenticate: Bearer realm="api"
	Allow: GET, HEAD, OPTIONS
	x-content-type-options: nosniff
	strict-transport-security: max-age=3600; includeSubDomains
	Set-Cookie: logged_in=; expires=Thu, 01-Jan-1970 00:00:00 GMT; Max-Age=0; Path=/, sessionid=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx; Domain=.www.safaribooksonline.com; expires=Mon, 26-Mar-2018 22:03:14 GMT; httponly; Max-Age=1209600; Path=/; secure, api_key=; expires=Thu, 01-Jan-1970 00:00:00 GMT; Max-Age=0; Path=/
	Content-Length: 58
	Accept-Ranges: bytes
	Date: Mon, 12 Mar 2018 22:03:12 GMT
	Via: 1.1 varnish
	Connection: keep-alive
	X-Client-IP: xxx.xx.xx.xxx
	X-Served-By: cache-sea1044-SEA
	X-Cache: MISS
	X-Cache-Hits: 0
	X-Timer: S1520892192.424554,VS0,VE432
	Vary: Accept, Accept-Language, Authorization, Cookie`

**Comment by lorenzodifuccia** [comment]
As you can see is an `Out-of-Session` message, so use the `--cred` argument in order to perform again the login.

**Comment by gabrielelana** [comment]
Unfortunately I have the same error with `--cred` argument with the same output

```
[13/May/2018 17:39:36] ** Welcome to SafariBooks! **
[13/May/2018 17:39:36] Logging into Safari Books Online...
[13/May/2018 17:39:38] Retrieving book info...
[13/May/2018 17:39:39] API: Out-of-Session (Authentication credentials were not provided.).

[13/May/2018 17:39:39] Last request done:
	URL: https://www.safaribooksonline.com/api/v1/book/9781491903063/
	DATA: None
	OTHERS: {}

	401
	Server: nginx/1.10.3 (Ubuntu)
	Content-Type: application/json
	Content-Language: en-US
	strict-transport-security: max-age=3600; includeSubDomains
	WWW-Authenticate: Bearer realm="api"
	x-xss-protection: 1; mode=block
	Allow: GET, HEAD, OPTIONS
	x-content-type-options: nosniff
	X-Frame-Options: SAMEORIGIN
	Set-Cookie: logged_in=; expires=Thu, 01-Jan-1970 00:00:00 GMT; Max-Age=0; Path=/, api_key=; expires=Thu, 01-Jan-1970 00:00:00 GMT; Max-Age=0; Path=/, sessionid=mhux5eznbvkpg1p8qtgrfqzua13lcwzh; Domain=.www.safaribooksonline.com; expires=Sun, 27-May-2018 15:39:40 GMT; httponly; Max-Age=1209600; Path=/; secure
	Content-Length: 58
	Accept-Ranges: bytes
	Date: Sun, 13 May 2018 15:39:39 GMT
	Via: 1.1 varnish
	Connection: keep-alive
	X-Client-IP: 2.39.28.199
	X-Served-By: cache-fra19150-FRA
	X-Cache: MISS
	X-Cache-Hits: 0
	X-Timer: S1526225979.798707,VS0,VE359
	Vary: Accept, Accept-Language, Authorization, Cookie
```

How does safari checks the login? Via cookies? I can see that the `get_book_info` is sending: `corp_sessionid`, `csrfsafari`, `BrowserCookie`, `original_referrer` and `sessionid`

How can I help you to debug more?

**Comment by lorenzodifuccia** [comment]
Thanks you!
I'll change the label of this issue to: `read before new issue` :smile:
