### ISSUE TITLE
"Login: no CSRF Token found in the page. Unable to continue the login. Try again..."

### ISSUE THREAD

**Issue by bitfield** [lorenzodifuccia/safaribooks#51]
Command:

```
python3 safaribooks.py --cred "john@bitfieldconsulting.com:xxx" 9781786468949
```

Output:

```

       ____     ___         _
      / __/__ _/ _/__ _____(_)
     _\ \/ _ `/ _/ _ `/ __/ /
    /___/\_,_/_/ \_,_/_/ /_/
      / _ )___  ___  / /__ ___
     / _  / _ \/ _ \/  '_/(_-<
    /____/\___/\___/_/\_\/___/

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[-] Logging into Safari Books Online...
[#] Login: no CSRF Token found in the page. Unable to continue the login. Try again...
[+] Please delete all the `<BOOK NAME>/OEBPS/*.xhtml` files and restart the program.
[!] Aborting...
```

[info_9781786468949.log](https://github.com/lorenzodifuccia/safaribooks/files/2639744/info_9781786468949.log)

**Comment by pierow2k** [comment]
Getting the same error.  Worked fine ~72 hours ago.

**Comment by gad0lin** [comment]
Same here

**Comment by pierow2k** [comment]
FWIW, the login page does still provide a form field with the `csrfmiddlewaretoken` value set.

baseURI:  https://www.safaribooksonline.com/accounts/login/

`<form action="/accounts/login/" id="login-form" method="post" class="js-login-view">
  <input type="hidden" name="csrfmiddlewaretoken" value="xXXxYXxXXxxYYXXXxxxYxXXxxXxXXXxxxXXYXxxXXXXxXxXXXYxXXXYxXxYxxxYx">`

**Comment by gad0lin** [comment]
got there as well :) moment ago through debugging 
Simplified solution:
https://github.com/lorenzodifuccia/safaribooks/pull/52

**Comment by pierow2k** [comment]
Just tested - it looks like that fixes the issue.

**Comment by Darkle** [comment]
That fix works for me as well. I think this might be related to the fact that https://www.safaribooksonline.com redirects to https://www.oreilly.com/ if you're not logged in.

**Comment by ricardont** [comment]
Worked

**Comment by lorenzodifuccia** [comment]
Thanks all, I changed and merged the @gad0lin pull request.
https://github.com/lorenzodifuccia/safaribooks/blob/master/safaribooks.py#L420

Let me know!
How much I love the Open Source community!!!

**Comment by racemus** [comment]
Now it says:
`[#] API: Out-of-Session (You do not have permission to perform this action.).`

**Comment by pierow2k** [comment]
> Now it says:
> `[#] API: Out-of-Session (You do not have permission to perform this action.).`

The December 4 commit is working fine for me.  I just did a fresh clone to confirm.

```bash
       ____     ___         _
      / __/__ _/ _/__ _____(_)
     _\ \/ _ `/ _/ _ `/ __/ /
    /___/\_,_/_/ \_,_/_/ /_/
      / _ )___  ___  / /__ ___
     / _  / _ \/ _ \/  '_/(_-<
    /____/\___/\___/_/\_\/___/

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[-] Logging into Safari Books Online...
[*] Retrieving book info...
[-] Title: xxxxxxxxxxxxxxxxxxxxxxxxx
[-] Authors: xxxxxxxxxxxxx
[-] Identifier: xxxxxxxxxxxxx
[-] ISBN: xxxxxxxxxxxxx
[-] Publishers: xxxxxxxxxxxxxxxx
[-] Rights: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
[-] Description: xxxxxxxxxxxxxxxxx…
```

**Comment by racemus** [comment]
What could be wrong in my case?

**Comment by lorenzodifuccia** [comment]
Already logged? SSO credentials?

**Comment by ricardont** [comment]
> How can I check I'm already logged?

I had a similar issue,  I logged in a browser first (which was asking me to pass a captcha), then I could download. Hope this help in your case

**Comment by lorenzodifuccia** [comment]
Try this new version and let me know!
Thanks for all the support :heart:

**Comment by pmduc2012** [comment]
Anyone have fixed this error?

[-] Logging into Safari Books Online...
[#] Login: no CSRF Token found in the page. Unable to continue the login. Try again...
[+] Please delete all the `<BOOK NAME>/OEBPS/*.xhtml` files and restart the program.
 [!] Aborting...

[info_9780135299555.log](https://github.com/lorenzodifuccia/safaribooks/files/3239466/info_9780135299555.log)

**Comment by kientt86** [comment]
Got the same error,

`[-] Logging into Safari Books Online...
[#] Login: no CSRF Token found in the page. Unable to continue the login. Try again...
[+] Please delete all the `<BOOK NAME>/OEBPS/*.xhtml` files and restart the program.
[!] Aborting...
`
