### ISSUE TITLE
[+] Please delete all the `<BOOK NAME>/OEBPS/*.xhtml` files and restart the program.

### ISSUE THREAD

**Issue by jeanvs80** [lorenzodifuccia/safaribooks#58]
[#] API: Out-of-Session (Authentication credentials were not provided.)
[+] Please delete all the `<BOOK NAME>/OEBPS/*.xhtml` files and restart the program.
[!] Aborting...

I can´t download the books

**Comment by sanjosan777** [comment]
It worked for me but recently stopped working with the same issue.
[-] Logging into Safari Books Online...
                                                                                                                        [*] Retrieving book info...
                                                                                                                        [#] API: Out-of-Session (Authentication credentials were not provided.).

                                                                                                                        [+] Please delete all the `<BOOK NAME>/OEBPS/*.xhtml` files and restart the program.
                                                                                                                        [!] Aborting...

I can log in to the site with the same credentials without any issue.
when  use the --no-cookies argument i get the following erorr

[-] Logging into Safari Books Online...
                                                                                                                        [*] Retrieving book info...
                                                                                                                        [#] Unhandled Exception: [WinError 2] The system cannot find the file specified: 'C:\\Users\\XYZ\\safaribooks\\cookies.json' (type: FileNotFoundError)
                                                                                                                        [+] Please delete all the `<BOOK NAME>/OEBPS/*.xhtml` files and restart the program.
                                                                                                                        [!] Aborting...

 Any thoughts on this ?
much appreciate if you can resolve this

**Comment by dexter101010** [comment]
Hello all. You see those errors because safari filter your ip.Even if you can login into the site, they filter requests from script.Change your ip and try again then let us all know if it's working.For me it's working like that.

**Comment by dexter101010** [comment]
This will solve your problem : 

https://github.com/lorenzodifuccia/safaribooks/pull/54

**Comment by lukogs** [comment]
![safaribooks](https://user-images.githubusercontent.com/44989688/50604757-fd363a80-0ee5-11e9-9f78-38eb5984d1d5.PNG)

Kindly share me possible solutions!

**Comment by lorenzodifuccia** [comment]
Try this new version and let me know!
Thanks for all the support :heart:

**Comment by lukogs** [comment]
@lorenzodifuccia -Thank you so much! it works like a charm.
