### ISSUE TITLE
Login: unable to perform auth login to Safari Books Online. 

### ISSUE THREAD

**Issue by fahim-sikder** [lorenzodifuccia/safaribooks#61]
Hey, I have updated the BASE_URL to https://learning.oreilly.com

But still getting the following errors. Any idea?

`[-] Logging into Safari Books Online...`                                         
`[#] Login: unable to perform auth login to Safari Books Online.`                 
`[*] Details:`
    `Unexpected error!`
`[+] Please delete all the `<BOOK NAME>/OEBPS/*.xhtml` files and restart the program.`
`[!] Aborting...`

**Comment by roboserg** [comment]
I am getting the same error!

**Comment by roboserg** [comment]
look here https://github.com/lorenzodifuccia/safaribooks/pull/54

**Comment by lorenzodifuccia** [comment]
Try this new version and let me know!
Thanks for all the support :heart:

**Comment by e24n1h2** [comment]
> Try this new version and let me know!
> Thanks for all the support ❤️

could you please share link for new version of script - I am also getting same error !

**Comment by eduarcor** [comment]
> > Try this new version and let me know!
> > Thanks for all the support ❤️
> 
> could you please share link for new version of script - I am also getting same error !

+1 Please, update the code!! Thanks

**Comment by naveennsit** [comment]
please update code

**Comment by naveennsit** [comment]
still gettiing same error
