### ISSUE TITLE
Multi-tasking Image download along with content download

### ISSUE THREAD

**Issue by LingarajVB** [lorenzodifuccia/safaribooks#62]
Just an amazing app, Kudos @lorenzodifuccia .

I wanted to request a feature, i.e., download takes time for large books even though the data connection speeds are high so, is it possible to enhance on that?
like, was there a way thought already for that? specially for image downloads.

- May be by adding a feature for multitasking?
- May be by making them as separate entities - like, 2 different jobs?

**Comment by lorenzodifuccia** [comment]
For O.S. different from Windows there's already a multiprocessing feature for images and CSSs downloading.
With Windows I had some problems and now I don't have time to handle this.
If anyone knows Python and multiprocessing in Windows, I would appreciate your help with a PR.
