### ISSUE TITLE
Body background color slows down my ebook reader

### ISSUE THREAD

**Issue by fedme** [lorenzodifuccia/safaribooks#63]
The script adds a style tag to every chapter page that sets the background of the body element. Having a background color on every page slows down and breaks the refresh of my Kobo ebook reader.

To remove the background color I changed line 211 from
`"body{{background-color:#fbfbfb!important;margin:1em;}}" \`
To:
`"body{{background-color:transparent!important;margin:1em;}}" \`

This fixed the issue for me, but I would like to ask why you were setting a background color to the body in the first place. 

If you agree that we don't actually need a body background color, I submitted a PR that you can merge :)

**Comment by arulk** [comment]
[Book Image](https://imgur.com/a/ba8Kwkb) I am seeing a dark background in my rendered epub. Not sure where this is coming from.  It is not part of the book as it renders clearly in the online reader.

**Comment by lorenzodifuccia** [comment]
Look at the PR:

> When you download a book without the `--kindle` flag it shows the background defined by the book's CSS. Instead, you will have a transparent background on kindle format of the ebook.

**Comment by amaltson** [comment]
@fedme have you found this working? I've tried the most recent version of the code with the `--no-kindle` option and it still has the background colour. I've also tried applying something similar to your change and it still has a background colour.

Is there any way to remove the `background-color` at all?
