### ISSUE TITLE
Unhandled Exception: [WinError 267] Directory name invalid

### ISSUE THREAD

**Issue by billhongs** [lorenzodifuccia/safaribooks#7]
[01/Mar/2018 17:38:49] ** Welcome to SafariBooks! **
[01/Mar/2018 17:38:49] Logging into Safari Books Online...
[01/Mar/2018 17:38:53] Retrieving book info...
[01/Mar/2018 17:38:55] Title: Revive: How to Transform Traditional Businesses into Digital Leaders
[01/Mar/2018 17:38:55] Authors: Brian Manning, Jason Albanese
[01/Mar/2018 17:38:55] Identifier: 9780134307626
[01/Mar/2018 17:38:55] ISBN: 9780134307626
[01/Mar/2018 17:38:55] Publishers: PH Professional Business
[01/Mar/2018 17:38:55] Description: GAME-CHANGING DIGITAL TRANSFORMATION:USE DIGITAL STRATEGIES, CHANNELS, AND PLATFORMS TO TRANSFORM ENTERPRISES TO COMPETE IN THE DIGITAL AGE Move from “reactive digital” to “transformative digital”  Use digital capabilities to fundamentally change the way you lead, direct, and structure organizations and teams  Stay focused on the “moving target” of digital best practices, and accelerate your progress towards digital maturity REVIVE will help you build a core business model for creating your own ...
[01/Mar/2018 17:38:55] Release Date: 2015-11-17
[01/Mar/2018 17:38:55] URL: https://www.safaribooksonline.com/library/view/revive-how-to/9780134307626/
[01/Mar/2018 17:38:55] Retrieving book chapters...
[01/Mar/2018 17:39:01]   File "safaribooks.py", line 992, in <module>
    SafariBooks(args_parsed)
  File "safaribooks.py", line 305, in __init__
    self.create_dirs()
  File "safaribooks.py", line 671, in create_dirs
    os.makedirs(self.BOOK_PATH)
  File "C:\apps\Python\Python36\lib\os.py", line 220, in makedirs
    mkdir(name, mode)

[01/Mar/2018 17:39:01] Unhandled Exception: [WinError 267] Directory name invalid : 'D:\\books\\safaribooks\\Books\\Revive: How to Transform Traditional Businesses into Digital Leaders' (type: NotADirectoryError)
[01/Mar/2018 17:39:01] Last request done:
	URL: https://www.safaribooksonline.com/api/v1/book/9780134307626/chapter/?page=3
	DATA: None
	OTHERS: {}

	200
	Server: nginx/1.10.3 (Ubuntu)
	Content-Type: application/json
	Content-Language: en-US
	X-Frame-Options: SAMEORIGIN
	x-content-type-options: nosniff
	Allow: GET, HEAD, OPTIONS
	strict-transport-security: max-age=3600; includeSubDomains, max-age=31536000; includeSubdomains
	x-xss-protection: 1; mode=block
	Content-Encoding: gzip
	Cache-Control: s-maxage=1800
	Content-Length: 770
	Accept-Ranges: bytes
	Date: Thu, 01 Mar 2018 09:39:01 GMT
	Via: 1.1 varnish
	Connection: keep-alive
	X-Client-IP: 111.204.128.114
	X-Served-By: cache-hnd18738-HND
	X-Cache: MISS
	X-Cache-Hits: 0
	X-Timer: S1519897141.881305,VS0,VE569
	Vary: Accept, Accept-Language, Authorization, Cookie

{"count":21,"next":null,"previous":"https://www.safaribooksonline.com/api/v1/book/9780134307626/chapter/?page=2","results":[{"archive":"https://www.safaribooksonline.com/api/v1/book/9780134307626/","content":"https://www.safaribooksonline.com/api/v1/book/9780134307626/chapter-content/index.html","url":"https://www.safaribooksonline.com/api/v1/book/9780134307626/chapter/index.html","natural_key":["9780134307626","index.html"],"full_path":"index.html","minutes_required":19.549999999999997,"next_chapter":{"title":"","web_url":""},"previous_chapter":{"url":"https://www.safaribooksonline.com/api/v1/book/9780134307626/chapter/epilogue.html","title":"Epilogue. Examples of Digital Trends Accelerating the Digital Revolution","web_url":"https://www.safaribooksonline.com/library/view/revive-how-to/9780134307626/epilogue.html"},"stylesheets":[{"full_path":"9780134307626.css","url":"https://www.safaribooksonline.com/library/css/revive-how-to/9780134307626/9780134307626.css","original_url":"https://www.safaribooksonline.com/library/view/revive-how-to/9780134307626/9780134307626.css"}],"images":[],"asset_base_url":"https://www.safaribooksonline.com/library/view/revive-how-to/9780134307626/","web_url":"https://www.safaribooksonline.com/library/view/revive-how-to/9780134307626/index.html","last_position":null,"videoclips":[],"publisher_scripts":"","publisher_script_files":[],"allow_scripts":false,"videoclip":null,"academic_excluded":false,"subjects":[{"name":"Business","description":""},{"name":"Business Communication","description":""}],"authors":[{"name":"Brian Manning"},{"name":"Jason Albanese"}],"cover":"https://www.safaribooksonline.com/library/cover/9780134307626/","book_title":"Revive: How to Transform Traditional Businesses into Digital Leaders","updated":"2017-03-07T17:29:38.821287Z","site_styles":["https://www.safaribooksonline.com/static/CACHE/css/b8d25f1a9a05.css"],"created_time":"2015-12-02T20:01:17.163719Z","last_modified_time":"2015-12-02T20:01:22.960804Z","filename":"index.html","path":"","epub_properties":null,"head_extra":null,"has_video":false,"title":"Index","description":"","virtual_pages":17}]}

**Comment by billhongs** [comment]
Some books have the same short book name on safaribooks.

**Comment by lorenzodifuccia** [comment]
I fixed this issue! Thanks again!
But I don't understand the last comment. What do you mean?

**Comment by billhongs** [comment]
Some books have the same short book name on safaribooks.

For example,the following two books have the same short name: Stepping Up

https://www.safaribooksonline.com/library/view/stepping-up/9781292186887/
https://www.safaribooksonline.com/library/view/stepping-up/9781609940584/

**Comment by lorenzodifuccia** [comment]
Ok, with the last commit I fixed this problem.
Thanks for helping me!

**Comment by billhongs** [comment]
def escape_dirname(dirname, clean_space=False):
        if ":" in dirname:
            if dirname.index(":") > 30:
                dirname = dirname.split(":")[0]

        for ch in ['\\', '/', '<', '>', '`', '\'', '"', '*', '?', '|']:
            if ch in dirname:
                dirname = dirname.replace(ch, "")

        return dirname if not clean_space else dirname.replace(" ", "")

this Statement maybe wrong，not 30 but 0
if dirname.index(":") > 30:

**Comment by lorenzodifuccia** [comment]
I voluntarily put 30 because I want to split only long title.
Example: there is a book called _"HTTP: The Definitive Guide"_. It's ok for me to display all the book title.
But I can say the same for a book like "Windows Internals, Part 1: System architecture, processes, threads, memory management, and more, Seventh Edition".
Maybe I have to reduce the range that I choose

**Comment by lorenzodifuccia** [comment]
Now is 15 chars

**Comment by billhongs** [comment]
def escape_dirname(dirname, clean_space=False):
        if ":" in dirname and dirname.index(":") > 15:
            dirname = dirname.split(":")[0]

        for ch in ['\\', '/', '<', '>', '`', '\'', '"', '*', '?', '|']:
            if ch in dirname:
                dirname = dirname.replace(ch, "")

        return dirname if not clean_space else dirname.replace(" ", "")

Running on Windows system, dirname cannot include ":“.

for ch in ['\\', '/', '<', '>', '`', '\'', '"', '*', '?', '|', **':'**]:
            if ch in dirname:
                dirname = dirname.replace(ch, "")

**Comment by lorenzodifuccia** [comment]
I always use Linux, so I don't cover well the problems on Windows.
I updated the program adding this fix.
