### ISSUE TITLE
API: Out-of-Session Issue Returned

### ISSUE THREAD

**Issue by andrewmpalka** [lorenzodifuccia/safaribooks#70]
It appears that the API:OOS issue has returned --yes, I'm up to date (jan 4 commit).
My account was banned (I knew this was a possibility) on top of this, so I'm going to assume that O'Reilly is starting to take action over this method.

**Comment by lorenzodifuccia** [comment]
Could you add some information?

**Comment by federico33385** [comment]
Hi Guys, 

Same over here, this is the output: 

`Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "safaribooks.py", line 810, in _thread_download_images
    for chunk in response.iter_content(1024):
AttributeError: 'int' object has no attribute 'iter_content'
[#] HTTPSConnectionPool(host='learning.oreilly.com', port=443): Max retries exceeded with url:`

**Comment by randoFelipe** [comment]
Anyone can give any help about this problem? I'm having this one too
`[-] Logging into Safari Books Online...                                                                                                                                                                            
[*] Retrieving book info...                                                                                                                                                                                        
[#] API: Out-of-Session (You do not have permission to perform this action.).                                                                                                                                      

[+] Please delete all the `<BOOK NAME>/OEBPS/*.xhtml` files and restart the program.                                                                                                                               
[!] Aborting...                   `

**Comment by federico33385** [comment]
I think that we can say this project was nice but now RIP, not sure there is a workaround to this.

**Comment by danx12** [comment]
Just run once providing your credentials, this will generate the cookie.json file. Then run again without your credentials. It worked for me.

**Comment by Pritpal25** [comment]
I have the very latest commit and I am getting this error again.

-] Logging into Safari Books Online...
[*] Retrieving book info...
[#] API: Out-of-Session (You do not have permission to perform this action.).

[+] Please delete all the `<BOOK NAME>/OEBPS/*.xhtml` files and restart the program.
[!] Aborting...

**Comment by Kambaa** [comment]
> I have the very latest commit and I am getting this error again.
> 
> -] Logging into Safari Books Online...
> [*] Retrieving book info...
> [#] API: Out-of-Session (You do not have permission to perform this action.).
> 
> [+] Please delete all the `<BOOK NAME>/OEBPS/*.xhtml` files and restart the program.
> [!] Aborting...
> 
> I tried to manually create the cookies.json file in the package where the script is, using the format provided [here](https://github.com/lorenzodifuccia/safaribooks/issues/2#issuecomment-367726544) and used the [code](https://github.com/lorenzodifuccia/safaribooks/issues/2#issuecomment-429343521) to fetch the values from my looged in browser for the values needed in the cookies file.
> 
> There was one that I couldnt find, corp_sessionid, except that I found everything replaced it with correct values and re-ran the script.
> 
> Failed with the same error as above.

i noticed that there's a groot_sessionid is placed. Anyone noticed this?
![image](https://user-images.githubusercontent.com/5601326/59701999-70ffa180-91ff-11e9-8ff0-8a3f2f24f026.png)

**Comment by vu-truong** [comment]
Same problem.
Has anyone solved this problem yet?

**Comment by okovwvrv** [comment]
Same issue unfortunately.

**Comment by gosse** [comment]
Same issue here

**Comment by peacej** [comment]
same issue here

**Comment by lixinf** [comment]
same issue
