### ISSUE TITLE
unicode exception

### ISSUE THREAD

**Issue by danilohgds** [lorenzodifuccia/safaribooks#72]
BookID:  9781617294839

[#] Unhandled Exception: 'charmap' codec can't encode character '\ufffd' in position 388: character maps to <undefined> (type: UnicodeEncodeError)

**Comment by lorenzodifuccia** [comment]
Could you provide more information? Like the content of the `9781617294839.log` file?

**Comment by lorenzodifuccia** [comment]
Duplicate #16
