### ISSUE TITLE
python trowing exception when downloading

### ISSUE THREAD

**Issue by anilpdv** [lorenzodifuccia/safaribooks#73]
> Error in sys.excepthook:
> Traceback (most recent call last):
>   File "safaribooks.py", line 98, in unhandled_exception
>     self.exit("Unhandled Exception: %s (type: %s)" % (o, o.__class__.__name__))
>   File "safaribooks.py", line 84, in exit
>     self.error(str(error))
>   File "safaribooks.py", line 81, in error
>     self.out(output)
>   File "safaribooks.py", line 67, in out
>     sys.stdout.write("\r" + " " * self.columns + "\r" + put.encode("utf-8", "replace") + "\n")
> TypeError: must be str, not bytes
> 
> Original exception was:
> Traceback (most recent call last):
>   File "safaribooks.py", line 1026, in <module>
>     SafariBooks(args_parsed)
>   File "safaribooks.py", line 274, in __init__
>     self.display.intro()
>   File "safaribooks.py", line 117, in intro
>     self.out(output)
>   File "safaribooks.py", line 67, in out
>     sys.stdout.write("\r" + " " * self.columns + "\r" + put.encode("utf-8", "replace") + "\n")
> TypeError: must be str, not bytes

**Comment by lgertel** [comment]
Same error here. Using macOS.

**Comment by infosisio** [comment]
Same here, was about to create an issue.

**Comment by muness** [comment]
Introduced by https://github.com/lorenzodifuccia/safaribooks/commit/c4f36279999cfa2152c8a1c6d401ee799c6497b0

**Comment by anilpdv** [comment]
thanks @muness changing the code to previous one worked for me.

**Comment by theshah392** [comment]
Has anyone figured this out?  Can there be an update?  I am not sure what to modify in the code...

**Comment by myliyifei** [comment]
> Introduced by [c4f3627](https://github.com/lorenzodifuccia/safaribooks/commit/c4f36279999cfa2152c8a1c6d401ee799c6497b0)

same issue, revert is work

**Comment by nich227** [comment]
I'm having the same error, but commenting out any instance of `self.out(...)` and `def out` makes it work, but there is no output except for the progress bar.

**Comment by lorenzodifuccia** [comment]
Pull last commit: b96819b
