### ISSUE TITLE
Out-of-Session (Authentication credentials were not provided.)

### ISSUE THREAD

**Issue by edison303** [lorenzodifuccia/safaribooks#78]
I've tried using --cred "email@domain.com:pass", as well as creating a cookies.json file based on the cookie contents in Firefox. Both give the same error, and the cookies.json is deleted.

In the browser, after I log into learning.oreilly.com, I'm redirected to my.safaribooksonline.com.

Anything I'm doing wrong?

**Comment by puneetguptanitj** [comment]
i am seeing this error as well . In the logs i see that it correctly logs in and even finds out how many chapters does the book have. 
But then fails with this error 
```
[#] API: [+] Use the `--cred` option in order to perform the auth login to Safari Books Online.
```
