### ISSUE TITLE
SSLError(SSLCertVerificationError

### ISSUE THREAD

**Issue by dhruv-bansal** [lorenzodifuccia/safaribooks#79]
Downloading book CSSs... (4 files)
[#] HTTPSConnectionPool(host='maxcdn.bootstrapcdn.com', port=443): Max retries exceeded with url: /font-awesome/4.4.0/css/font-awesome.min.css (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1045)')))
[#] Error trying to retrieve this CSS: /Users/dhruvbansal/Documents/setup/safarionlinebook_ddownloader/lorenzodifuccia/safaribooks/Books/Mastering Spring Cloud (9781788475433)/OEBPS/Styles/Style03.css
    From: https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css
[#] Unhandled Exception: 'int' object has no attribute 'content' (type: AttributeError)
[+] Please delete all the `<BOOK NAME>/OEBPS/*.xhtml` files and restart the program.
[!] Aborting...

**Comment by Jamconnect** [comment]
Same
