### ISSUE TITLE
public library

### ISSUE THREAD

**Issue by marcstreeter** [lorenzodifuccia/safaribooks#80]
any ideas/info on what would be needed to make this work with the public library? I am very interested in this and with some direction would be willing to contribute a large chunk of the implementation (or whole chunk).

**Comment by KtodaZ** [comment]
Same, I'm interested too and could contribute to development.

**Comment by lorenzodifuccia** [comment]
Create your own fork and PR it. Thanks!

**Comment by JarnoRFB** [comment]
Do you mean for cases when you don't have login credentials, but just have access to vpn? I would be highly interested as well, as this is the case in my university.

**Comment by lorenzodifuccia** [comment]
U cannot access ORLY only with VPN. Maybe you're under SSO with your University credentials. Try to follow the topics for Single Sign On (SSO) opened as Issue into this project and let me know. (TL;DR: copy the ORLY cookies from your browser into a file called cookies.json and run the script)

**Comment by JarnoRFB** [comment]
Ok our university is providing access via https://proquestcombo.safaribooksonline.com/ instead of oreily learning. The cookies that I get from the site do not really seem to match with what you would usually get from SSO
```json
{
"optimizelyEndUserId":"oeu1551619064368r0.6679886506413864",
"optimizelySegments":"%7B%22757067938%22%3A%22direct%22%2C%22778703350%22%3A%22false%22%2C%22781081607%22%3A%22gc%22%2C%22949601412%22%3A%22none%22%7D",
"optimizelyBuckets":"%7B%7D",
"cookie-monster":"true",
"_ga":"GA1.3.928953731.1551619431",
"ki_r":"",
"ki_t":"1551619431114%3B1560434269882%3B1560437787111%3B2%3B6",
"_gid":"GA1.3.1868332445.1560770929",
"Safari":"cookieversion=2&cookie-monster=true&portal=proquestcombo&key=ED5389112F6DA8AD1D0239750367567617E4EA446008DAECE467994C9BE21B42599F721DE257F194C1F65E21824CD2C7CA0930CE2635F6EB1E068251CDE5918020CF936BD9535488EA34C57E4559F6E75EF67D12E38346C595CF6FD5AD96EEA2A4C8E4B909242A91CDD2E4EE7CDA48B3183C9443A042DDA6AA698D3C8A&sessionid=1b9073f5-6297-44d0-bd28-80c49dc2b06b&ref=Undefined&logged=true&a=",
"State":"reader=html&displaygrbooks=0&action=1&view=book&xmlid=9780134686097&isbn=9780134686097&query=&uicode=Osnabrueck&PromoCode=&HttpReferrer=https%3a%2f%2fproquestcombo.safaribooksonline.com%2fredirect%3fredirectpage%3d%252f9780134686097%26key%3d20CD33436B04F2ABC9519B54CA1592035F69A49DD&portal=proquestcombo"
}
```

Did anyone try this before?

**Comment by lorenzodifuccia** [comment]
@JarnoRFB, I think that the `Safari` entry in that dictionary contains all the cookies needed.
Try to see the network requests made to O'RLY after the "SSO" login to figure out which cookies are really involved.
