### ISSUE TITLE
Apple Books format too slim and grey background

### ISSUE THREAD

**Issue by superandrew** [lorenzodifuccia/safaribooks#83]
On Apple Books, the epub has two problems:

The first problem is that the epub doesn't use the whole screen space, instead, it formats the content into two slim columns, see screenshot. I launched it with the --no-kindle option, but I would like to understand if there any (maybe undocumented/untested) parameter to change those two behaviors, or if it depends on the book.

![Screenshot 2019-03-24 at 11 05 05](https://user-images.githubusercontent.com/71364/54877942-b5101f80-4e25-11e9-9750-c80485fb2828.png)

**Comment by sinstein** [comment]
It seems like this could be a problem with the specific book. I have a bunch of ebooks I read on iBooks and I do not see either of the issues you have mentioned.

![safaribooks_epub_ibooks](https://user-images.githubusercontent.com/4283218/56654092-d7a78980-66ac-11e9-8f0f-ab74cdebe695.png)

**Comment by lorenzodifuccia** [comment]
The `--no-kindle` option leaves the original CSS rules (in other words: the same background color) of the online view. Try without this flag.

**Comment by lorenzodifuccia** [comment]
The other issue, the two columns view, it is the default view on 's Book app.
Try with View > Single Page    or   ⌘1

**Comment by paraglohiya** [comment]
Hi,

![Screen Shot 2019-07-28 at 6 12 47 PM](https://user-images.githubusercontent.com/15009804/62013646-5526de00-b163-11e9-8392-7be8fb44f1ff.jpg)

I am also facing the same issue. When using the --no-kindle option - background becomes gray.
The page size is still very small for Books app on Apple

**Comment by amaltson** [comment]
I have the same thing happen with two different books, and when I load them on the Kobo they're deathly slow and crash the Kobo 😢

**Comment by lorenzodifuccia** [comment]
Try to download the new version of the code and then convert the EPUB to EPUB using Calibre, in order to remove any format issues.
