### ISSUE TITLE
Encoding Error '\u2019'

### ISSUE THREAD

**Issue by danielctrl** [lorenzodifuccia/safaribooks#87]
**Book Id**: 9781484237519

### **Console output:**

> [*] Retrieving book info...
> [#] Unhandled Exception: 'charmap' codec can't encode character '\u2019' in position 106: character maps to <undefined> (type: UnicodeEncodeError)
> [+] Please delete all the `<BOOK NAME>/OEBPS/*.xhtml` files and restart the program.
> [!] Aborting...

**Comment by lorenzodifuccia** [comment]
Exec this command before run the script:
`set PYTHONIOENCODING=:replace`
then:
`python3 safaribooks.py ...`

Source: https://stackoverflow.com/questions/5419/python-unicode-and-the-windows-console/32176732#32176732
