### ISSUE TITLE
SSO support

### ISSUE THREAD

**Issue by lprokein** [lorenzodifuccia/safaribooks#9]
Hi, is it somehow possible to use SSO instead on username & pwd? Thanks

**Comment by lorenzodifuccia** [comment]
Sign into Safari Books with your SSO and copy all the cookies to `cookies.json` file. If you don't provide the `--auth` option, the program will search/use the cookies stored in that file.
See the format on #2.

**Comment by turkerbdonmez** [comment]
here is the cookie i get from university proxy

s_fid=3CD8FE139675B736-1E7433589B0A1B8A; s_v17=%5B%5B%27ENG%27%2C%271536847875593%27%5D%5D; s_nr2=1536847875596-New; MuseProxySessionID=017z3fpmoazevv
