### ISSUE TITLE
ePUB created will not import into Google Books

### ISSUE THREAD

**Issue by Brando27615** [lorenzodifuccia/safaribooks#90]

**Comment by Brando27615** [comment]
I've tried a few of the books on the site, and while they look OK in Calibre, Google Books, nor Calibre will convert them at all. I tried the --no kindle option also. Again, the Calibre viewer seems to be fine so far, but nothing else for ePUBs. I'll continue trying other books, but I thought it might be something obvious I am missing here.

**Comment by absay** [comment]
My Google Play Books won't even process the uploads correctly. I only get a "Processing failed" after a while.

**Comment by giny8i8** [comment]
Same here, Google books yields "processing failed" messages, but the funny thing is, that this does not happen every time! There are failing books and passing ones, all generated by the program. Strange.

**Comment by lorenzodifuccia** [comment]
Can you convert the EPUB with Calibre? I didn't understand.
In case, try to convert `EPUB to EPUB` using Calibre. Then use the Calibre's EPUB to upload to biG.

**Comment by Brando27615** [comment]
Yes, I use Calibre for all of my conversions. The OI'Relly books fail
processing every time.

I can, however, read them with other ePub readers including Calibre's own
reader and others I have downloaded for Android.

Apple's ePub reader works also. I have ALL of my stuff in Google Books and
it's a bit frustrating.

Thank you for this utility!!!

**Comment by Brando27615** [comment]
OK all, I think I have a workaround. It's obviously not anything to do with the utility.

Here is how to make the downloaded ePub Safari Book work in Google Books:

1. Take the resultant .ePub from the utility and launch Calibre
2. Add the Book, left most green icon
3. Select the book and click convert. 
4. For the Output Format, select "Mobi" (I confirmed this by downloading it to my Kindle)
5. Delete the book from Calibre
6. Add the book back as a Mobi
7. Select Convert again
8. Select ePub

The final file I was able to upload successfully to Google Books.

**Comment by megaroeny** [comment]
This worked for me, converting via Calibre! I downloaded my source file from https://unbound.com/, which was the cause of the issue I guess.

**Comment by duyetmai** [comment]
There are many error when checking file with epub validator. That's why google playbook cannot read.
http://validator.idpf.org/

**Comment by dpthegrey** [comment]
> OK all, I think I have a workaround. It's obviously not anything to do with the utility.
> 
> Here is how to make the downloaded ePub Safari Book work in Google Books:
> 
> 1. Take the resultant .ePub from the utility and launch Calibre
> 2. Add the Book, left most green icon
> 3. Select the book and click convert.
> 4. For the Output Format, select "Mobi" (I confirmed this by downloading it to my Kindle)
> 5. Delete the book from Calibre
> 6. Add the book back as a Mobi
> 7. Select Convert again
> 8. Select ePub
> 
> The final file I was able to upload successfully to Google Books.

yes, Google Play Books accepts the epub after the workaround but in my case the few pages(chapters) got out of order and I was not able to navigate properly. So, I had to remove from google books and the only option available left was to use downloaded epub directly in apple books. 

Also, after this conversion apple books says the epub is corrupted.

**Comment by DavitHin** [comment]
> > OK all, I think I have a workaround. It's obviously not anything to do with the utility.
> > Here is how to make the downloaded ePub Safari Book work in Google Books:
> > 
> > 1. Take the resultant .ePub from the utility and launch Calibre
> > 2. Add the Book, left most green icon
> > 3. Select the book and click convert.
> > 4. For the Output Format, select "Mobi" (I confirmed this by downloading it to my Kindle)
> > 5. Delete the book from Calibre
> > 6. Add the book back as a Mobi
> > 7. Select Convert again
> > 8. Select ePub
> > 
> > The final file I was able to upload successfully to Google Books.
> 
> yes, Google Play Books accepts the epub after the workaround but in my case the few pages(chapters) got out of order and I was not able to navigate properly. So, I had to remove from google books and the only option available left was to use downloaded epub directly in apple books.
> 
> Also, On opening the epub after conversion the apple books app prompts the epub is corrupted.

Yes, it's true Hope the developer could adjust some code and make it work with Google PlayBook.

It's better than iBook for apple....

**Comment by lorenzodifuccia** [comment]
> Can you convert the EPUB with Calibre? I didn't understand.
> In case, try to convert `EPUB to EPUB` using Calibre. Then use the Calibre's EPUB to upload to biG.

Have you tried to convert the EPUB from safaribook to EPUB with Calibre? This will fix many of the CSS/Page layout/TOC problems. Just EPUB to EPUB. Calibre will rise many error/warning, just ignore them and take the fully EPUB-spec compliant output obtained by Calibre.

I use Apple Books without problems after converting the safaribooks output to a new ebup.
If you installed calibre on your PC, maybe you can also use the command line version:
`ebook-convert <safaribook>.epub <safaribook>_CLEAR.epub`
