### ISSUE TITLE
Error while logging in

### ISSUE THREAD

**Issue by Leggy7** [lorenzodifuccia/safaribooks#94]
> [#] Login: no CSRF Token found in the page. Unable to continue the login. Try again...                                                                                                               
> [+] Please delete all the `<BOOK NAME>/OEBPS/*.xhtml` files and restart the program.                                                                                                                 
> [!] Aborting... 

tried to specify different login url, changing to
> SAFARI_BASE_HOST = "www.oreilly.com"
> LOGIN_URL = SAFARI_BASE_URL + "/member/"
or
> LOGIN_URL = SAFARI_BASE_URL + "/member/login/"

result is still the same. By inspecting the page I cannot find any tag like this
> input[@name='csrfmiddlewaretoken']

how can I fix this?

**Comment by TheNullable** [comment]
For not wait to an official fix, you can use the default `cookies.json` file with a valid session of your account in O'Reilly, and you are ok to download books.

**Comment by lukogs** [comment]
![image](https://user-images.githubusercontent.com/44989688/57978415-2b4a9000-7a2b-11e9-82b5-e4e1d0ca565b.png)
 But Books folder is Empty still facing the same challenge
Could you help me to resolve this

**Comment by joshmaerk** [comment]
Take a look to Issue [#92](https://github.com/lorenzodifuccia/safaribooks/issues/92)

**Comment by lukogs** [comment]
Python37\lib\site-packages\urllib3\connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings

After adding lines shown in issue #92 Above shown lines were shown & in result to that we got same response as shown above.

Kindly suggest!

**Comment by ardenne21** [comment]
Hi all, after updating the code from issue #92, I still see the same error message and I am not able to download. Does anyone still have problems?

**Comment by grepmeister** [comment]
The youtube-dl project fixed their login problem, see 
https://github.com/ytdl-org/youtube-dl/commit/a9e03736dfb2038d6a569e6305f4ac727a8ac71b

**Comment by LavrenkovNV** [comment]
autorization not work.
help please.
sorry for English.

**Comment by andims** [comment]
the same here! 
[#] Login: no CSRF Token found in the page. Unable to continue the login. Try again...

**Comment by andims** [comment]
I have also tried export cookies as json using the chrome extension "EditThisCookie"  and store its values to the file cookie.json and got the error:
python3 safaribooks.py  xxx-book_id
#Unhandled Exception: 'list' object has no attribute 'items' (type: AttributeError)

**Comment by andims** [comment]
Please @lorenzodifuccia accept @joshmaerk  pull request! 
he fixed the  csrf login issue 
https://github.com/joshmaerk/safaribooks/tree/fix-%2392

thanks u guys nice project

**Comment by lorenzodifuccia** [comment]
I pushed some changes on the login process. Let's see if works...

**Comment by guillaumevincent** [comment]
Thank you @lorenzodifuccia, I will test it!

**Comment by stomanin** [comment]
The fix worked for me too, thank you
