### ISSUE TITLE
Problem Downloading CSS files

### ISSUE THREAD

**Issue by tony109** [lorenzodifuccia/safaribooks#95]
Getting errors while downloading css

`[-] Downloading book CSSs... (4 files)                                                                                                 
[#] HTTPSConnectionPool(host='learning.oreilly.com', port=443): Max retries exceeded with url: /static/CACHE/css/ec784807e120.css (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:2305)'),))
[#] Error trying to retrieve this CSS: /root/safaribooks/Books/Practical Security (9781680506679)/OEBPS/Styles/Style01.css             
    From: https://learning.oreilly.com/static/CACHE/css/ec784807e120.css
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "./safaribooks.py", line 795, in _thread_download_css
    s.write(response.content)
AttributeError: 'int' object has no attribute 'content'
[#] HTTPSConnectionPool(host='learning.oreilly.com', port=443): Max retries exceeded with url: /static/css/annotator.e3b0c44298fc.css (Caused by SSLError(SSLError(1, '[SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2305)'),))
[#] Error trying to retrieve this CSS: /root/safaribooks/Books/Practical Security (9781680506679)/OEBPS/Styles/Style02.css             
    From: https://learning.oreilly.com/static/css/annotator.e3b0c44298fc.css
Process Process-3:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "./safaribooks.py", line 795, in _thread_download_css
    s.write(response.content)
AttributeError: 'int' object has no attribute 'content'
`

**Comment by lorenzodifuccia** [comment]
Error says `SSLError [...OMITTED...] [SSL: WRONG_VERSION_NUMBER]`.
This issue is related to:
- Your PC/Network,
- O'RLY Server/Network,
- Astral Constellations.

Closing...
