### ISSUE TITLE
Would be great if we can download videos are well

### ISSUE THREAD

**Issue by HeavyMavi** [lorenzodifuccia/safaribooks#98]
Please consider creating a new program for videos download.

**Comment by hoangphuc2019** [comment]
you can download safaribooksonline video with youtube-dl tools. Check it out on github

**Comment by HeavyMavi** [comment]
but it doesn't allow to download the whole course.

**Comment by lorenzodifuccia** [comment]
https://github.com/lorenzodifuccia/safaribooks/issues/18#issuecomment-404793589

**Comment by hoangphuc2019** [comment]
> but it doesn't allow to download the whole course.

1/ you should upgrade to latest version of youtube-dl
2/ Don't use cookies to download video. It would works with credentials (username and password).
